### ISSUE TITLE
Failed to establish new connection

### ISSUE THREAD

**Issue by ashuein** [cokelaer/bioservices#100]
While trying to work with the KEGG parser tool (or any other tool) I encounter the connection error problem.

"HTTPConnectionPool ... ... , [Errno 111] Connection Refused"

I know that this is because of the proxy settings which is required for internet access. So, can someone tell me how to change proxy settings for the "Bioservices package"?

**Comment by cokelaer** [comment]
@ashuein is it still an issue ? I have test locally and could access to KEGG. All tests succeed as well in the master version of bioservices right now. Do you have a piece of code to test ? thanks

**Comment by cokelaer** [comment]
works for me and on travis. I will close this issue for now.
