### ISSUE TITLE
How do I get all of the D#s for Cardiovascular agents under Brite?

### ISSUE THREAD

**Issue by LomSpace** [cokelaer/bioservices#101]
What method do I use to get the D#s for all of the cardiovascular agents under brite? When I execute  `print(k.get("br:br08364"))` an xml file is returned. I want the list of entries for each cardiovascular agent.

**Comment by LomSpace** [comment]
Is there a parser for the xml file?

**Comment by cokelaer** [comment]
It looks like brite data setes do not follow the same convention as other resources from KEGG. So, what is returned is  a pure HTML file. This means that the bioservices parser cannot parse the format (HTML).  Sorry about that but I do not see any solution for now except to find a output format from KEGG that can be parsed.

**Comment by LomSpace** [comment]
That was quick. Well what ever I come up with I'll share KEGG.

MGAVI

*Mgavi Elombe Brathwaite, MSc.*
*Project Manager and Academic Adviser*
*Bioinformatics Program*
*NYU Tandon School of Engineering*

**Comment by cokelaer** [comment]
I'll close this issue for now but feel free to reopen it if you have a solution in the future. thanks

**Comment by LomSpace** [comment]
​Thomas,

That's fine and and thanks!

Mgavi​

*Mgavi Elombe Brathwaite, MSc.*
*Project Manager and Academic Adviser*
*Bioinformatics Program*
*NYU Tandon School of Engineering*
