### ISSUE TITLE
License statements inconsistent

### ISSUE THREAD

**Issue by mbargull** [cokelaer/bioservices#102]
Looking at the source files' headers, it is apparent that your software is licensed under the *GPLv3*.

However there are contradicting statements in your `setup.py` and `LICENSE` files. In summary there are the following inconsistent statements:
- `src/bioservices/*.py`: `#  Distributed under the GPLv3 License.`
- `setup.py`: `'license' : 'GPL'` (no version specified!)
- `setup.py`: `      'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)',`
- `LICENSE`: `Bioservices is distributed under a 3-clause ("Simplified" or "New") BSD license.`

**Comment by cokelaer** [comment]
Thanks for spotting the discrepancies. The original license was GPLv3 so I have set GPLv3 in the different places you have mentioned. thanks again.

**Comment by mbargull** [comment]
Great, thanks!
