### ISSUE TITLE
obtaining list of gene IDs from a br or ko number

### ISSUE THREAD

**Issue by LomSpace** [cokelaer/bioservices#106]
Hello,
When I query with the  list or get methods, I often get an int returned. I figure that the int is the number of items returned. I want the actual items. What am I missing. Forgive me if it's right in front of me, but I new to bioservices.

Best,
Mgavi

**Comment by cokelaer** [comment]
Please provide a test example so that I can reproduce the issue

**Comment by cokelaer** [comment]
for book-keeping, the returned number could be 404 meaning the request is invalid;
