### ISSUE TITLE
Query runs too long in BioMart

### ISSUE THREAD

**Issue by LomSpace** [cokelaer/bioservices#110]
I have figured out how to get the attributes and filters to set up my BioMart Query. I'm connecting to Ensembl as the host, but my queries run for hours without returning anything. Check out my code:

```
Python 3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "copyright", "credits" or "license()" for more information.
>>> #import bioservices and biomart
>>> from bioservices import *
>>> # create a biomart object
>>> # Actually, you first create the connection to biomart data at ensemble
>>> # it actually does not matter which order, whether you create the object or
>>> # the http connection.
>>> b.host='www.ensembl.org'
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    b.host='www.ensembl.org'
NameError: name 'b' is not defined
>>> # Yes it does. You have to create the object first
>>> b=BioMart(verbose=False)
>>> # Now we'll use the lookfor function to see it there is a mart that contains
>>> # our word that's passed as an argument to the  lookfor method.
>>> b.lookfor('snp')
You must set the host (e.g. f.host='www.ensembl.org' 
>>> b.host='www.ensembl.org'
>>> b.lookfor('snp')
Candidate:
     database: sequence_mart_90 
    MART name: ENSEMBL_MART_SNP 
  displayName: Ensembl Variation 90 
        hosts: www.ensembl.org 
Candidate:
     database: snp_mart_90 
    MART name: ENSEMBL_MART_FUNCGEN 
  displayName: Ensembl Regulation 90 
        hosts: www.ensembl.org 
>>> # There are two marts that meet our search criteria. Now we'll use the
>>> # mart name to retrieve the datasets
>>> b.datasets("ENSEMBL_MART_FUNCGEN")
['mmusculus_external_feature', 'hsapiens_motif_feature', 'hsapiens_annotated_feature', 'hsapiens_mirna_target_feature', 'mmusculus_mirna_target_feature', 'mmusculus_regulatory_feature', 'dmelanogaster_external_feature', 'hsapiens_external_feature', 'hsapiens_regulatory_feature', 'mmusculus_annotated_feature', 'mmusculus_motif_feature']
>>> datasets = b.datasets("ENSEMBL_MART_FUNCGEN")
>>> for d in datasets:
	print(d)
```
	
mmusculus_motif_feature
dmelanogaster_external_feature
mmusculus_regulatory_feature
hsapiens_external_feature
hsapiens_regulatory_feature
mmusculus_annotated_feature
hsapiens_mirna_target_feature
mmusculus_mirna_target_feature
mmusculus_external_feature
hsapiens_motif_feature
hsapiens_annotated_feature

```
>>> # We'll explore hsapiens_annotated_feature. We first add it to the
>>> # add_dataset_to_xml method
>>> b.add_dataset_to_xml("hsapiens_annotated_feature")
>>> # Let's get the list of attributes of this dataset. These are the keys of the of the dictionary returned by attributes("hsapiens_annotated_feature")
>>> attributes=b.attributes("hsapiens_annotated_feature")
>>> # Let's turn those keys into a list
>>> attribute_k = attributes.keys()
>>> for a in attribute_k:
	print(a)
```
	
efo_id
chromosome_name
chromosome_start
chromosome_end
feature_type_name
feature_type_class
feature_type_description
epigenome_name
epigenome_description
project_name
archive_id
so_accession
so_name
```
>>> # Now we can start the move towards completing our query
>>> b.add_attribute_to_xml("so_accession")
>>> xmlq = b.get_xml()
>>> ret = b.query(xmlq)
```
Any ideas on how to resolve this and get a return file?

**Comment by DarthGecko** [comment]
I've had luck with the Phytozome database. See if any of my code helps you out? I'll try to help you more later if it doesn't. 
[phytozomedler.py](https://github.com/DarthGecko/orthometer/blob/master/phytozomedler.py)

**Comment by LomSpace** [comment]
Nick, 
I'll see what can be used to solve my issue. 

Thanks!
Mgavi

**Comment by LomSpace** [comment]
Not getting anywhere.

**Comment by cokelaer** [comment]
For testing, I had to replace "hsapiens_annotation_feature" from the code above with "hsapiens_external_feature".

Then, I tried your commands up to the end

```
ret = b.query(xmlq)
```
and got an answer in 3-4 seconds.

What is going on sometimes (actully often) is that the biomart service are updated, or down and in such case the query hangs forever. This is independent of bioservices unfortunately.

I'm closing this issue since we now know that the query works.

**Comment by LomSpace** [comment]
Thomas,

Thanks for the follow-up! I was teaching a bioinformatics course and
covered this feature and basically explained to the students that biomart
service was probably being updated. I really appreciate the follow-u[!

Best,
Mgavi

*Mgavi Elombe Brathwaite, MSc.*
*Program Manager and Academic Adviser*
*Bioinformatics Program*
*NYU Tandon School of Engineering*
