### ISSUE TITLE
the documentation is off line

### ISSUE THREAD

**Issue by aurelBZH** [cokelaer/bioservices#120]
Hi, 
thanks for the work on bioservices! 
Everything is in the title, the documentation return an 404 error , when i try to connect. 
thanks by advance
Aurélien Béliard

**Comment by cokelaer** [comment]
what documentation are you refering to ?
The official documentation here: http://bioservices.readthedocs.io/en/master/ seems to work

**Comment by aurelBZH** [comment]
ok sorry it's just the link https://pythonhosted.org/bioservices/ in the readme which is not working.

**Comment by cokelaer** [comment]
will be fixed in the close future by fixing the links in the README file.
