### ISSUE TITLE
clustered uniprot query

### ISSUE THREAD

**Issue by jotech** [cokelaer/bioservices#121]
Hi, I'm struggling to get [this query](https://www.uniprot.org/uniref/?query=uniprot:(ec%3A1.1.1.282+taxonomy%3Abacteria+AND+reviewed%3Ayes)+identity:0.5) done with bioservices.
I started with
```python
u.search("ec:1.1.1.282+and+taxonomy:bacteria+and+reviewed:yes")
```
but do not know how to get the clustered search done (simply adding ``+identity:0.5`` doesn't work).

**Comment by cokelaer** [comment]
sorry for the later answer. it looks like what you try to do is not a 100% uniprot request. 

The code include is a uniprot request. However, the "+identity:0.5" seems to be understood by UniRef only.

I have no solution for now. Indeed, I could not find the UniRef service on the EBI website. 

maybe it is worth contacting EBI asking how to do it programmatically. 

From their webpage, I can see uniprot entry (available in bioservices) but no information about uniref (https://www.uniprot.org/help/programmatic_access) as of June 2018.
