### ISSUE TITLE
uniprot search produces additional hits not related with the query

### ISSUE THREAD

**Issue by joaquinabian** [cokelaer/bioservices#122]
```
u = uniprot.UniProt()
print(u.search('P12345', columns= 'id, entry name, comment(SUBCELLULAR LOCATION)'))

Entry	Entry name	Subcellular location [CC]
P12345	AATM_RABIT	SUBCELLULAR LOCATION: Mitochondrion matrix {ECO:0000250}. Cell membrane {ECO:0000250}.
A1Z2X0	A1Z2X0_9STRA	SUBCELLULAR LOCATION: Mitochondrion inner membrane {ECO:0000256|RuleBase:RU000369}; Multi-pass membrane protein {ECO:0000256|RuleBase:RU000369}.
P35520	CBS_HUMAN	SUBCELLULAR LOCATION: Cytoplasm {ECO:0000269|PubMed:17087506, ECO:0000269|PubMed:23981774}. Nucleus {ECO:0000269|PubMed:17087506}.
```

**Comment by cokelaer** [comment]
I believe that the uniprot website returns the reviewed entries only. In bioservices, we returns the reviewed and unreviewed entries.

Using the reviewed:yes filter gives you 2 entries:
```
u.search("P12345+AND+reviewed:yes", columns="id,entry name, comment(SUBCELLULAR LOCATION)"))

Entry	Entry name	Subcellular location [CC]
P12345	AATM_RABIT	SUBCELLULAR LOCATION: Mitochondrion matrix {ECO:0000250}. Cell membrane {ECO:0000250}.
P35520	CBS_HUMAN	SUBCELLULAR LOCATION: Cytoplasm {ECO:0000269|PubMed:17087506, ECO:0000269|PubMed:23981774}. Nucleus {ECO:0000269|PubMed:17087506}.
```

Here, I do not know why we get two entries but if you specifically ask for P12345 and reviewd entries on uniprot website: http://www.uniprot.org/uniprot/?query=p12345+AND+reviewed%3Ayes&sort=score then you also get two entries like in bioservices.

My feeling is that if a query without any filters is used on the uniprot.org website, then the best hit is shown (even though you have several entries; this was not the case before). On the contrary, if you set a filter (here reviewed:yes or reviewed:no), then all entries are shown in a table.

so the additional hits are correct hits according to the uniprot algorithm (I do not know the details). You have to filter them out or just keep the first (best) entry. Alternatively, you can add other filters yourself.

For instance, if you know the taxon, set it in the query:
```
    u.search("P12345+AND+reviewed:yes+AND+taxonomy:9984")
```
Note also that you can use the **get_df** method that returns a dataframe with all columns::
```
    u.get_df("P12345+AND+reviewed:yes+AND+taxonomy:9984")
```

**Comment by JB-MS** [comment]
Hi,

if still relevant, making the query specific to Uniprot IDs  did the trick for me, i.e.:

`u.search("id:P12345")`

Cheers,
Johannes

**Comment by cokelaer** [comment]
Perfect. Thanks a lot that answers the questions. I have add a small paragraph in the documentation that will appear online in the next release
