### ISSUE TITLE
How to run Bioservices through a proxy connection ?

### ISSUE THREAD

**Issue by ashuein** [cokelaer/bioservices#127]
I am facing the issue of HTTP Connection Refused error while using Bioservices package. The problem is due to the proxy settings required to access the internet. Although system proxy is set properly but seems the Bioservices package needs to define it separately.

Can you let me know how to change the proxy internet settings for the Bioservices?

**Comment by cokelaer** [comment]
sorry @ashuein if you find a solution I would be happy to accept the pull request or add the code but I will not have time to look at this issue in the close future.

**Comment by ashuein** [comment]
Can you at least tell me what package Bioservices uses to fetch data from the internet ? Is it GET, POST or REQUESTS. A proxy handler will have to be defined and added to the package.

**Comment by JamesPino** [comment]
WSDL/SOAP or REST protocols

**Comment by achillesrasquinha** [comment]
How about passing a proxy list to the Service API and maybe use it across all services?

**Comment by cokelaer** [comment]
@ashuein 
There is a tentative of proxy  implementation now in version 1.7.8 
In the old-style bioservices services, you would use:

```
from bioservices import YOUR_FAVORITE_SERVICE
c = YOUR_FAVORITE_SERVICE()
c.proxies = {
"https": "https://0.0.0.0/whaetever,
"http": "https://0.0.0.0/whaetever
}
```
and in the new style implementation:
```
from bioservices import YOUR_FAVORITE_SERVICE
c = YOUR_FAVORITE_SERVICE()
c.services.proxies = {
"https": "https://0.0.0.0/whaetever,
"http": "https://0.0.0.0/whaetever
}
```
I have not done ant special tests just a quick implementation. As @achillesrasquinha mentioned, the requests package has it already. I hope it works. I won't have the time to test for now.
