### ISSUE TITLE
wikipathways findPathwaysByText returned empty list

### ISSUE THREAD

**Issue by EricSHo** [cokelaer/bioservices#131]
Hi,

I have repeated the example to retrieve pathways related to 'MTOR'.

s.findPathwaysByText('mtor')

I tried on two Macs, one returned 117 rows, the other returned zero! Both are installed with Python 3.6 and the latest bioservices.

After a bit of digging, I nailed it down to these two lines inside function findPathwaysByText(...) in wikipathways.py:

data = self.easyXML(request.content)       
data = data.findAll("ns1:result")

The first data contained html statements but the second data returned by data.findall(...) was empty.

The variable data from the Mac that worked properly contained the following:

...
<ns1:result>
<ns2:score>0.027740808</ns2:score>
<ns2:id>WP3154</ns2:id>
<ns2:url>https://www.wikipathways.org/index.php/Pathway:WP3154</ns2:url>
<ns2:name>AMPK Signaling</ns2:name>
<ns2:species>Bos taurus</ns2:species>
<ns2:revision>90026</ns2:revision>
</ns1:result>, <ns1:result>
...

What might be wrong? Your help is appreciated.

Eric.

**Comment by cokelaer** [comment]
I got the same issue indeed. I will check this out. Not sure whether the XML format changed or whether it is an issue in the easyXML method.

**Comment by cokelaer** [comment]
I just tried on another machine using bioservices 1.5.2 and it works now... Can you check the version of bioservices and let me know the answer:

    import bioservices
    bioservices.version

**Comment by cokelaer** [comment]
Needs to refactor this services using new REST interface.

**Comment by cokelaer** [comment]
Planned for version 1.6.0

**Comment by cokelaer** [comment]
This issue probably occured in all methods. All methods have been updated to use the json format instead of XML. It is more robust and less prone to errors if the XML format changes. Now available on pypi version 1.6.0
