### ISSUE TITLE
BioMart not taking kindly to setting host

### ISSUE THREAD

**Issue by ivirshup** [cokelaer/bioservices#133]
Here's a quick example:

```python
>>> from bioservices import BioMart
>>> mart = BioMart(host="www.ensembl.org")
>>> mart.registry()
You must set the host (e.g. f.host='www.ensembl.org' 
>>> mart.host is None
True
>>> mart.host = "www.ensembl.org"
>>> mart.registry()
You must set the host (e.g. f.host='www.ensembl.org' 
>>> mart.host is None
True
>>> import bioservices
>>> bioservices.__version__
'1.5.2'
```

I think this might be the cause of [an issue in the scanpy package](https://github.com/theislab/scanpy/issues/242).

**Comment by zqfang** [comment]
Any progress here? I have the same problem here

**Comment by ivirshup** [comment]
I've been writing little wrappers for `biomaRt` or using [`pybiomart`](https://github.com/jrderuiter/pybiomart) (though I have had an open PR there for a bit).

**Comment by cokelaer** [comment]
This is working in the latest version of bioservices. I've just tried and the registry() calls works fine for me. 

The biomart service inside bioservices works in general but unfortunately the biomart service itself may be down from time to time as reported several times in bioservices issues. I believe this is independent of bioservices. Sorry for the inconvenience.

**Comment by ivirshup** [comment]
Could you post the code that worked for you? I'm still getting the same behavior on `1.6.0`, which I'll expand on:

First, even when the services are working, I cannot set the host to `www.ensembl.org`. I'm pretty sure this is due to [this line](https://github.com/cokelaer/bioservices/blob/d0581d322dd8cc730ac3d9d51fe48d56f3778898/src/bioservices/biomart.py#L237) checking the the response to `HEAD` was 200. If it's not the right region, for me at least, it returns a 302 (a redirect). However, if it were a `GET` request instead of a `HEAD`, the response will be 200. 

```python
>>> import requests
>>> requests.head("http://asia.ensembl.org/biomart/martservice").status_code
200
>>> requests.head("http://www.ensembl.org/biomart/martservice").status_code
302
>>> requests.get("http://www.ensembl.org/biomart/martservice").status_code
200
```

As a consequence of this, I'm pretty sure ensembl's BioMart service will still respond correctly to out-of-region requests. Here's an example of it seeming to work:

```python
>>> mart_manual = BioMart()
>>> mart_manual._host = "www.ensembl.org"
>>> mart_manual.url = f"https://{mart_manual._host}/biomart/martservice"
>>> mart_manual.registry()
[{'database': 'ensembl_mart_94', 'default': '1', 'displayName': 'Ensembl Genes 94', 'host': 'www.ensembl.org', ... }]
>>> mart_auto = BioMart("www.ensembl.org")
>>> mart_auto.registry()
You must set the host (e.g. f.host='www.ensembl.org' 
```

Second, I think there should be an example of it working, as examples in the docs don't run (as `mart.host` is never set):

```python
# from the top of `BioMart.__doc__` to the first error
>>> from bioservices import *
>>> s = BioMart()
>>> ret = s.registry()
You must set the host (e.g. f.host='www.ensembl.org' 
>>> s.names
You must set the host (e.g. f.host='www.ensembl.org' 
>>> "unimart" in s.names
You must set the host (e.g. f.host='www.ensembl.org' 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by fbrundu** [comment]
I have a question regarding the following lines (which may explain why the service is failing):

https://github.com/cokelaer/bioservices/blob/9240c6cfe23e2a50198272deb6c79e51b1ff01e0/src/bioservices/biomart.py#L208-L225

`url` and `host` variables are referenced as local, object variable and private (with leading underscore). I wasn't able to understand the logic behind this, maybe the naming is wrong?
Because, for example, replacing line 224 with `self._host = host` seems to fix the problem with the host, but probably also the `url` variable should be update (it's now "undefined").
Probably there's no error here, but could you please take a look?

This also affects [this module](https://github.com/theislab/scanpy/issues/242).
