### ISSUE TITLE
Update pathwaycommons.py

### ISSUE THREAD

**Issue by IgorRodchenkov** [cokelaer/bioservices#135]
Some code and docs in 
https://github.com/cokelaer/bioservices/blob/master/src/bioservices/pathwaycommons.py 
need updating to reflect the latest PC web services api (PC10 release): http://www.pathwaycommons.org/pc2/swagger-ui.html 
(e.g., _id-mapping_'s gone, _top_pathways_ got new parameters, etc.)

**Comment by IgorRodchenkov** [comment]
Me or someone from PC team will look into this and submit a new PR once done.

**Comment by CPerscheid** [comment]
Has this been resolved meanwhile? 
The PathwayCommons webservice currently even cannot be used to retrieve pathways in SIF format because the _valid_formats parameter does not contain the "SIF" keyword (only the formerly used "BINARY_SIF").

**Comment by cokelaer** [comment]
Dear @CPerscheid 
I have updated the code in pathwayscommon module. 

- id_mapping method is removed (obsolet). 
- added 4 new methods related to the sifgraph service. 
- Fixed the keyword (BINARY_SIF is now SIF, BINARY_EXTENDED is now TXT)

This is ready in the main master branch if you wish. I'll release a new version of bioservices later during the week.

**Comment by CPerscheid** [comment]
Dear @cokelaer, great to hear - thanks a lot!
