### ISSUE TITLE
How to set settings.TIMEOUT variable for eFetch()

### ISSUE THREAD

**Issue by arnome** [cokelaer/bioservices#141]
Hi,

I have a script with bioservices and `eUtils()`. I need to get nucleotide information in `genbank rettype` and I use `eFetch()` to do so. On every run, the error message is the same `read timeout`. 
The complete message is
![image001](https://user-images.githubusercontent.com/1922179/51251113-cc034300-1998-11e9-9a3b-174a0d1d3471.png)

 So, I wonder how I can set the «settings.TIMEOUT» var.
Thanks a lot,
arnome.

**Comment by cokelaer** [comment]
By default timeout is set to 30 seconds. you may want to increase it using:
```
e.TIMEOUT = 60
```
