### ISSUE TITLE
Uniprot mapping has server side bug when given gene names containing commas

### ISSUE THREAD

**Issue by ricosaurus** [cokelaer/bioservices#142]
This is not a bioservices issue AFAIK.  It looks like Uniprot's internal mapping fails when given a gene name that contains a comma.  For example, if "ADE5,7", (Bifunctional purine biosynthetic protein) is submitted via the REST service or website  will return separate mappings to 'ADE5' and '7'.  Perhaps there is a way of escaping the comma but I haven't found it.
```

import urllib
url = 'https://www.uniprot.org/uploadlists/'
params = {
'from':'GENENAME',
'to':'AC',
'format':'tab',
'query':'ADE5,7'
}

data = urllib.parse.urlencode(params).encode("utf-8")
request = urllib.request.Request(url, data)
response = urllib.request.urlopen(request)
page = response.read(200000)

```
page returns 
b'From\tTo\nADE5\tA0A088AL04\nADE5\tA0A0A9WZ50\nADE5\tA0A0C9RA29\nADE5\tA0A0F7U0A0\nADE5\tA0A0F8CZX8\nADE5\tA0A1C1CDM2\nADE5 ...\n7\tV5R8G8\n7\tV5R902\n7\tV5R9K0\n7\tV5R9M4\n7\tV5RBG9\n7\tV5RBP4\n7\tV5RC48\n7\tV5UQZ3\n7\tV5UQZ6\n7\tV5URI1\n7\tW0LIH5\n7\tW0LIW3\n7\tW0LJ48\n7\tW0LMM3\n7\tW0LNE0\n7\tW0LNH2\n7\tW0LNP8\n7\tW0LNV8\n7\tW0LPE9\n7\tW6AU08\n7\tW6PPN1\n7\tW6Q7A1\n7\tW8FQ64\n7\tW8FXH0\n7\tX2KNC7\n7\tX2KQX4\n7\tX2KRE7\n7\tX2KSR1\n7\tX2KTL2\n7\tX2KTQ9\n7\tX2KZA0\n7\tX4YDA8\n'

>

**Comment by cokelaer** [comment]
hello, that quite unfortunate. commas are indeed reserved characters for URL request. I have tried a few things using urllib.parse.quote to replace the comma, I have tried to replace it with 2%C but no success. This needs to be solved from uniprot side I believe. I have no solution for now. I keep this issue open though

**Comment by cokelaer** [comment]
looks like it is resolved in newest API
