### ISSUE TITLE
KEGG to UniProt was not working due to the list index out of range

### ISSUE THREAD

**Issue by ShahidIqb** [cokelaer/bioservices#143]
u.mapping(fr='KEGG_ID', to='ACC', query='hsa:1845')
Traceback (most recent call last):

  File "<ipython-input-26-392c561874bd>", line 1, in <module>
    u.mapping(fr='KEGG_ID', to='ACC', query='hsa:1845')

  File "/home/shahid/anaconda3/lib/python3.6/site-packages/bioservices/uniprot.py", line 359, in mapping
    result_dict[key].append(values[i])

IndexError: list index out of range

I updated the line#356 in bioservices/uniprot.py file and it's working for me
            # bug fix based on ticket #19 version 1.1.2
            # the default dict set empty list for all keys by default
            from collections import defaultdict
            result_dict = defaultdict(list)

            **keys = result[1::2]  #changed from 0 to 1**
            values = result[1::2]
            for i, key in enumerate(keys):
                result_dict[key].append(values[i])
        return result_dict

**Comment by ShahidIqb** [comment]
But still there are problems and it does not get the complete list. Please have a look

**Comment by cokelaer** [comment]
It works for me (feb 2020). This is a recurrent issue. I believe this is the uniprot service that may be failing from time to time. Not sure whether your solution fixes the issue. I'm closing this issue for now until further notice
```
u.mapping(fr='KEGG_ID', to='ACC', query='hsa:1845')
Out[3]: defaultdict(list, {'hsa:1845': ['P51452']})
```
