### ISSUE TITLE
Uniprot disconnecting after 43 requests

### ISSUE THREAD

**Issue by Jnbrooks** [cokelaer/bioservices#145]
Hello,

I have written a function to convert protein-identifiers of many different formats to uniprot-ids, in order to collect the FASTA sequence for further analysis. I am working with datasets of several thousand proteins. I tested my code with lists of 10, but when I tried to scale up I received the following error:

> CRITICAL[bioservices:UniProt]:  ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> CRITICAL[bioservices:UniProt]:  Issue. Maybe your current timeout is 100 is not sufficient. 
> Consider increasing it with settings.TIMEOUT attribute

By trial and error, I've found that the maximum number of requests I can send is, oddly, 43. 

My coding background is mostly focused on bioinformatics/statistics; almost everything I know about url requests I have learned while working on this project over the past month. But I've tried everything I could find by googling and poking through code, so I thought I'd submit the problem to some experts.

-----
**I call:**

> getFasta(Items, FileName = "ZTMassSpec",Input=False,Species=False,ReturnMetadata=True)
Items is a list of ~2000 proteins ids in the format "symbol_species"

**My code:**

`
```
import time
import re
import sys, io
from contextlib import redirect_stdout
grab = io.StringIO()

import requests
requests.session.__init__(headers = {"useragent": "Python **email address**"})

from cachecontrol import CacheControl
sess = requests.session()
cached_sess = CacheControl(sess)


import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import statsmodels.nonparametric.api as smnp
# or: https://peakutils.readthedocs.io/en/latest/reference.html
from scipy.signal import find_peaks

#https://www.sciencedirect.com/science/article/pii/S0006349516342692
#https://pappulab.github.io/localCIDER/
import localcider
from localcider import plots
from localcider.sequenceParameters import SequenceParameters
lc = SequenceParameters

#https://nbviewer.jupyter.org/gist/newgene/6771106
#https://mygene-py.readthedocs.io/en/latest/
import mygene
ProtIds = mygene.MyGeneInfo()

#https://biopython.org/
#http://biopython.org/DIST/docs/tutorial/Tutorial.html#htoc14
from Bio import Entrez
from Bio import SwissProt
from Bio import SeqIO
Entrez.email = ****

#https://bioservices.readthedocs.io/en/master/references.html#module-bioservices.uniprot
import bioservices
from bioservices import *
u = UniProt(verbose=False)
u._valid_columns = ['id','entry name','reviewed','sequence', 'feature(ALTERNATIVE SEQUENCE)']
u.__init__(cache=True)
settings.defaultParams['user.email'][0]=*****
settings.defaultParams['general.timeout'][0] = 1000 #give the server time?
settings.defaultParams['cache.on'][0] = True
settings.defaultParams['general.max_retries'][0] = 10 #give the server time?


def getFasta(proteins, FileName="temp", Species = 'Human', Input="uniprot", 
             columns = False, isoforms = False, ReturnMetadata = False, SequenceTable = True):
    
    if not isinstance(proteins,list):
        try:
            proteins = list(proteins)
        except:
            return ("Protein Set should ideally be a list or list-convertable")

    returnables = {"Search Messages":"No ID-search errors","Search Errors": "No FASTA-recovery errors"}
    error_list = pd.DataFrame()
    
    if columns:
         u._valid_columns += columns

#If necessary: Convert input to search terms for bioservices 
    if Input:
        if Input== "uniprot":
            proteins = [re.sub("^","id:",p) for p in proteins]
        
        else:
            try: 
                with redirect_stdout(grab): #to collect the messages MyGene spits out
                    grab.flush()
                    UniprotQuery = ProtIds.querymany(proteins, scopes = Input, species = Species, 
                                                 as_dataframe = True, fields="uniprot.Swiss-Prot", returnall=True)

                proteins=UniprotQuery['out']["uniprot.Swiss-Prot"]
                proteins.update(proteins[proteins.notna()].replace({"^":"id:"},regex=True))
                temp = proteins[proteins.isna()
                NotFound = np.column_stack([temp.index.format(),len(temp)*"No Uniprot ID Found".split("/")])
                error_list = error_list.append(pd.DataFrame(NotFound),ignore_index = True)

            except:
                if "temp" in locals().keys():
                    if len(temp) == len(proteins):
                        print ("Did you enter 'symbol', 'uniprot', or another input recognized by the MyGene package?:"
                                + " http://docs.mygene.info/en/latest/doc/data.html#available-fields") 
                else:
                    print ("Did you enter 'symbol', 'uniprot', or another input recognized by the MyGene package?:"
                               + " http://docs.mygene.info/en/latest/doc/data.html#available-fields")

            #When "mygene" doesn't return the uniprot ID, change to something else that bioservices might use
            if Species:
                proteins = proteins.fillna({x: x+"_"+Species for x in proteins[proteins.isna()].index}, axis = 'index')

            proteins = list(proteins)
        
#Search UniProt for protein metadata.

    limit = 40 #limit seems to be 43
    chunk = min(limit, len(proteins))
    N, rest = divmod(len(proteins), chunk)
    Metadata = pd.DataFrame()
    for i in range(0, N):
        Metadata = Metadata.append(u.get_df(proteins[i * chunk:(i + 1) * chunk]))
        time.sleep(60) #give the server time?
    
    Metadata = Metadata.append(u.get_df(proteins[N * chunk:N * chunk+rest]))
```
`

There is more, but the traceback points to that last line. 
I've tried to run it on different internet connections, and waited 12 hours in between calls in case I was temporarily banned from the server (although I can always call Items[0:43], so I don't think I've been banned).

It's possible that this is a problem on the Uniprot end, but let me know if you have any insights or need more information.

Thanks!

**Comment by cokelaer** [comment]
Hello, I do not think this is a bioservices issue. And indeed, you are not black-listed. I have set a limit of 3 requests per seconds as requested by those services. Yet, this is a real issue. The request is slow. Sometimes it is so slow that you wait for ever. I have experienced this issue. 

What is going on when you call **u.get_df** is that is calls the **u.search** function. That function is calling the uniprot API directly. 

If you try::

    u.search("zap70")

On my machine, this meant about 5-10 seconds and it returns about 20,000 entries. However, the first time it took about 30 seconds !! As if new requests are longer. 

One way to decrease the request time is to specify the organism:

    u.search("zap70+AND+organism:9606")

This returns only 186 entries in 0.5 seconds.
Another way is to use the limit argument to e.g; 10 or even 1 to keep the most relevant entry from the search:

    u.search("zap70+AND+organism:9606", limit=1)

takes 0.3 seconds sometimes even less (100ms).

finally, if you know the exact name, it is even better:

    u.search("ZAP70_HUMAN, limit=1)

also about 100ms
