### ISSUE TITLE
unhelpful ArrayExpress error messages

### ISSUE THREAD

**Issue by ec339** [cokelaer/bioservices#148]
### observed issue
when passing a non-expected parameter via queryAE(), the resulting error message is unhelpful

`UnboundLocalError: local variable 'sets' referenced before assignment`

### reproduction
I tried supplying 'date="2015*"' before realising 'date' isn't a valid parameter:

`aeobj = arrayexpress.ArrayExpress()
ids = aeobj.queryAE(date="2015*", species="rat", exptype='transcription profiling')
print(ids)`

### suggestions

- in the '_search()' method, devtools.check_param_in_list (line 187) should by default return an error message such as 
`ValueError: Incorrect value provided (date). Correct values are ['foo', 'bar']`. 
This default error message is probably prevented by the 'try' in line 382

- If the above behaviour is correct and the 'try' should be maintained (at the cost of the normal error messaging), then the exception at line 384 should provide a meaningful error message, and the script should exit there (currently line 385 is 'pass', so the exception does nothing)

**Comment by cokelaer** [comment]
Thanks for reporting this issue. Indeed, this is not very informative. I have now fixed this specific issue. I'll have added a note for other similar issue where devtools attributes is used. For that specific case, I just rewrote the code in pure Python.
