### ISSUE TITLE
BiGG Models

### ISSUE THREAD

**Issue by achillesrasquinha** [cokelaer/bioservices#153]
Integration for [BiGG Models](http://bigg.ucsd.edu/)

**Comment by cokelaer** [comment]
Dear @achillesrasquinha 
This looks like a good integration for bioservices. At the moment, at will not have the time to integrate it though. I am currently updating other services already available and maintaining the whole software. If you want to help to add it, please have a go. I'll be more than happy to help you in the process. best

**Comment by achillesrasquinha** [comment]
Pull Request #157

**Comment by cokelaer** [comment]
brilliant. integrated now in bioservices v1.7.4
