### ISSUE TITLE
UniProt(cache=True) doesn't recall UniProt_bioservices_db.sqlite after kernel restart 

### ISSUE THREAD

**Issue by GianArauz** [cokelaer/bioservices#161]
Hi bioservices community,

This is my first time opening a GitHub issue, and thus I would like to apologize in advance for any formal mistake or misunderstanding I could exhibit when doing so.

After initiating the UniProt object as follows (first snippet):
`from bioservices import uniprot as up`
`UP = up.UniProt(cache=True)`

I can use the `.get_df()` method to perform a UniProt query this way (second snippet):
`ac_list = ['P0C6X7', 'P0C6U8', 'P59632']`
`query_list = ['id:' + ac for ac in ac_list]`
`UP.get_df(query_list)`

When doing this, the UniProt object locally stores the query in the `UniProt_bioservices_db.sqlite` file located in `C:\Users\you\AppData\Local\bioservices\bioservices\`. If I rerun the last two snippets, the UniProt object detects that the first query was identical to the second one, and thus loads the result from the first query locally stored in the `*.sqlite` file instead of bombarding the UniProt servers again.

What I found is that if I restart the Python kernel and I rerun the code, the UniProt object cannot load the result from the first query locally stored in the `*.sqlite` file, and unnecessarily connects to UniProt and appends the same query result to the existing `*.sqlite` file.

I do not know if this behavior is deliberately like this or if it could be something unnoticed. In any case, I think it could be great keeping the cache behavior after restarting the Python kernel session. Is this possible? Or is it something chimerical?

Thanks in advance for your time.

Gian.

**Comment by cokelaer** [comment]
Dear Gian, thanks for using / looking into bioservices. 
That's an interesting issue. The cache system was implemented a long time ago and seems to work in general. from the issue you repported regarding the kernel, it is not intended. I've never noticed this issue. Is this in a jupyter notebook  ? How can I reproduce this locally (kernel restart)  ? thanks a lot; 
Thomas

**Comment by GianArauz** [comment]
Hi Thomas,

I can generate this issue either with Spyder IDE (v4.1.3) or JupyterLab (v1.2.6) running in a Windows 10 machine. To reproduce it:
1. Delete the `UniProt_bioservices_db.sqlite.sqlite` file.
2. Run this code chunk:
```
import time
from bioservices import uniprot as up

UP = up.UniProt(cache=True)

ac_list = ['P0C6X7', 'P0C6U8', 'P59632']
query_list = ['id:' + ac for ac in ac_list]

i = time.time()
UP.get_df(query_list)
f = time.time()
print(f'Slow first query: {f - i} s.')

i = time.time()
UP.get_df(query_list)
f = time.time()
print(f'Fast second query: {f - i} s.')
```
You should get something like:
```
Slow first query: 1.1925182342529297 s.
Fast second query: 0.07878947257995605 s.
```
3. Restart kernel (With Spyder, in the "Consoles" tab, pick "Restart kernel". With JupyterLab, in the "Kernel" tab, pick "Restart Kernel...").
4. Run the previous code chunk again. You should get almost the same output, consisting in a slow first query and a fast second query:
```
Slow first query: 1.159797191619873 s.
Fast second query: 0.08078479766845703 s.
```
I would expect two fast queries after restarting the kernel, because the first code chunk execution already generated the `UniProt_bioservices_db.sqlite.sqlite` file containing the data that I would like to (re-)query again in the second code chunk execution:
```
Slow first query: 0.07878613471984863 s.
Fast second query: 0.06781864166259766 s.
```
The point here is that, if we restart the python kernel, the `UniProt(cache=True)` can't recall the data stored in the `UniProt_bioservices_db.sqlite.sqlite` file, and unnecessarily interrogates the UniProt servers again, which is slow. It seems that the `cache=True` is not working properly.

Hope this helps Thomas.

PS: I'm a bioservices user. Thank you so much for developing this tool.
