### ISSUE TITLE
Retrieving subcellular location from UniProt is bugged

### ISSUE THREAD

**Issue by gezmi** [cokelaer/bioservices#163]
Hi All,

First, thank you for this package, it is really easy to use and fast.

I am trying to use UniProt service and retrieve subcellular location among other data.
Acoording to UniProt API description, it should be retrieved with "comment(SUBCELLULAR LOCATION)". However, the package does not accept this and asks for "feature(SUBCELLULAR LOCATION)" - but results in an empty column. Could you fixed this?

Thank you!

**Comment by Erik-White** [comment]
This is confusing, the correct value is `comment(SUBCELLULAR LOCATION)` according to the API. The API doesn't seem to have changed at any point [according to the wayback machine](https://web.archive.org/web/20150511181631/http://www.uniprot.org/help/uniprotkb_column_names).

It was changed to the current incorrect `feature(SUBCELLULAR LOCATION)` in https://github.com/cokelaer/bioservices/issues/124. So, it just needs changing back again
