### ISSUE TITLE
"'int' object is not subscriptable" when extracted genes in KEGG pathway

### ISSUE THREAD

**Issue by kshz2145714** [cokelaer/bioservices#165]
Hi there,
I want to make a dictionary of {pathwayID: [gene_id]}; key is the pathwayID and value is the gene in this pathway.
I tried 
```
k.organism = "acan"
s = KEGG()
data = s.get("path:acan00730")
dict_data = s.parse(data) 
gene_list = list(dict_data["GENE"].keys())
pathway_gene_dict["path:acan00730"] = gene_list
```
Above is working well. However, when I added a for loop
```
pathway_gene_dict = {}
k.organism = "acan"
k.pathwayIds
for pathway in k.pathwayIds:
    s = KEGG()
    data = s.get(pathway)
    dict_data = s.parse(data)
    gene_list = list(dict_data["GENE"].keys())
    pathway_gene_dict[pathway] = gene_list
```
It turned out to have "TypeError: 'int' object is not subscriptable" at this step `gene_list = list(dict_data["GENE"].keys())`
Could you tell me how can I correct it or any recommended way to get such a pathwayID dictionary?
Thank you in advacne.
best regards,
Stallworth

**Comment by Erik-White** [comment]
This error can be caused by trying to access the index of a non-iterable type, i.e. something that is not a tuple, list, dict etc. In this case the error is telling you that you're trying to access `dict_data` using the `GENE` key, but `dict_data` is an `int` and  does not support that.

I could also be caused by trying to initialise a new list with something that is not iterable, such as an integer.

I do not use this package so I'm afraid I can't tell you exactly what you need to do to fix this. However, from looking at the code, it appears that `KEGG.get()` may return an error code of `404` to indicate 'not found'. `KEGG.parse()` then returns `404` instead of a dictionary of results, resulting in your `TypeError: 'int'`.

Fortunately it is easy to check your result before trying to access it:
```
    dict_data = s.parse(data)
    if isinstance(dict_data, dict):
        gene_list = list(dict_data["GENE"].keys())
        pathway_gene_dict[pathway] = gene_list
    else:
        ...
```

**Comment by kshz2145714** [comment]
@Erik-White Thank you for your comment;
However, When I did not use the for-loop, I checked the type of these variation;
```
k.organism = "acan"
s = KEGG()
data = s.get("path:acan00730")
dict_data = s.parse(data) 
type(dict_data) # dict
type(dict_data['GENE'] # dict
gene_list = list(dict_data["GENE"].keys())
type(list(gene_dict.keys())) # list
pathway_gene_dict["path:acan00730"] = gene_list
```
It seems that if there is no for-loop, they are in right type. But when it changes to for-loop, it changes to `int`, which is confusing to me.

By the way, I tried the code you commented before, but bioservices:kegg is not working now; The Warning is below
```
INFO    [bioservices:KEGG]:  Initialising KEGG service (REST)
WARNING [bioservices:keggparser]:  Found keyword REL_PATHWAY, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (acan00010                   Pathway) into github.com/bioservices. Thanks T.C.
```

**Comment by Erik-White** [comment]
With your first example you are getting the results for a single pathway, which does return the correct data from the KEGG service. When you run your loop you are trying to get data for _every_ pathway in `KEGG.pathwayIds`. One or more of those pathways does not return the correct data and returns a status code instead.

The warning is saying that the acan00010 pathway has returned data with the key `REL_PATHWAY`, which it doesn't know how to parse. This shouldn't matter unless you actually need that specific data, the rest will get parsed.

I'll try and put together a quick code snippet that does what you're after

**Comment by Erik-White** [comment]
Here is a working example:
```
from bioservices import KEGG

# Initialize the KEGG service
k = KEGG()
k.organism = "acan"

# Initialize a dictionary to store the results
pathway_genes = dict()

for pathway in k.pathwayIds:
    data = k.get(pathway)
    data_parsed = k.parse(data)

    # Only retrieve a list of genes if the data was parsed correctly
    genes = list()
    if isinstance(data_parsed, dict) and "GENE" in data_parsed.keys():
        genes = list(data_parsed["GENE"].keys())

    # Store the results
    pathway_genes[pathway] = genes
```

The results are stored in the dictionary `pathway_genes` which looks like this:
```
path:acan00010 ['ACA1_177380', 'ACA1_066870', 'ACA1_175190', 'ACA1_201580', 'ACA1_368710', 'ACA1_200220', 'ACA1_191150', 'ACA1_053240', 'ACA1_275720', 'ACA1_284230', 'ACA1_095900', 'ACA1_142390', 'ACA1_068670', 'ACA1_244790', 'ACA1_054920', 'ACA1_071120', 'ACA1_050180', 'ACA1_280650', 'ACA1_049990', 'ACA1_012270', 'ACA1_164050', 'ACA1_287370', 'ACA1_288720', 'ACA1_042250', 'ACA1_038550', 'ACA1_093760', 'ACA1_309320', 'ACA1_205990', 'ACA1_191500', 'ACA1_230800', 'ACA1_231010']
path:acan00040 ['ACA1_089330', 'ACA1_089760', 'ACA1_342510', 'ACA1_139810', 'ACA1_222730', 'ACA1_036900', 'ACA1_187280', 'ACA1_054920', 'ACA1_071120', 'ACA1_050180', 'ACA1_291490', 'ACA1_366600', 'ACA1_175510']

etc
```

**Comment by kshz2145714** [comment]
@Erik-White 
Thank you so much, it works!

**Comment by Erik-White** [comment]
No problem :thumbsup:
