### ISSUE TITLE
AttributeError: 'ArrayExpress' object has no attribute 'info'

### ISSUE THREAD

**Issue by zqfang** [cokelaer/bioservices#168]
I got a bug in ArrayExpress module. I think `self.info` should be `self.logging.info`

https://github.com/cokelaer/bioservices/blob/0a35f31803dc504247ca114af63e4fa510ccb399/src/bioservices/arrayexpress.py#L394-L398

**Comment by cokelaer** [comment]
This is now fixed in the version 1.7.6 posted on pypi and on the master branch
