### ISSUE TITLE
The values of Column database(Ensembl) are not complete

### ISSUE THREAD

**Issue by thudxz** [cokelaer/bioservices#174]
I use the following code to search:
`u.search("organism:" + speciesID, columns = "id,entry name,protein names,database(Ensembl)")`

The returned values of Column database(Ensembl) are not complete. 

For example, the ensembl ids of **Q91UZ8** should be _"ENSMUST00000053073﻿; ENSMUSP00000056148﻿; ENSMUSG00000051486"._ While the returned ensembl ids are _"ENSMUST00000053073﻿;"_.

**Comment by cokelaer** [comment]
First of all thanks for using Bioservices/UniProt.

From UniProt, via BioServices or directly from uniprot website there is only one ensemble id  https://www.uniprot.org/uniprot/?format=tab&columns=id%2Centry+name%2Cprotein+names%2Cdatabase%28Ensembl%29&sort=score&query=Q91UZ8

that is : ENSMUST00000053073

Where to do you get the 2 other IDs ?  UniProt may focus on the transcript only whereas here ENSMUSG00000051486 seems to be related to the gene ?

**Comment by thudxz** [comment]
> Where to do you get the 2 other IDs ? UniProt may focus on the transcript only whereas here ENSMUSG00000051486 seems to be related to the gene ?

Thank you for your reply. I just searched in the Uniprot website: https://www.uniprot.org/uniprot/Q91UZ8. Here is the screenshot.
![Bioservices](https://user-images.githubusercontent.com/8584923/93159900-d5cae400-f741-11ea-9142-e9638a7ec0ca.PNG)

The IDs  ensembl database are transcript, protein and gene ID.

**Comment by cokelaer** [comment]
I tried again this example. Indeed, only one entry for ensembl is returned. This is is the output of the request, I believe this is another bug on the server side (I say another because other similar issues have been reportd. e.g. when a comma exists in the query name). Unfortunately, I cannot do anything about it. We can contact uniprot and let them know about that issue.

**Comment by cokelaer** [comment]
New uniprot API has been released last year. 

Redoing the example above, the syntax is now:

    print(u.search("Q91UZ8", columns = "id,accession,xref_ensembl"))
    Entry Name	Entry	Ensembl
    Q91UZ8_MOUSE	Q91UZ8	ENSMUST00000053073.6;

still only one ensemble ID. I assume this is the uniprot API 
Closing the issue.
