### ISSUE TITLE
KEGG error 503

### ISSUE THREAD

**Issue by shashany** [cokelaer/bioservices#175]
Hi,
I've been trying to use the bioservices instance of KEGG in the last two days and keep getting a 503 error every time.
It used to work very well until very recently.
Do you have an idea on why this is happening?

Thanks,
Shany

**Comment by CPerscheid** [comment]
I do not have an answer, but I have exactly the same problem. KEGG webservice seems to be broken, maybe they have changed something in the API at KEGG side.

**Comment by shashany** [comment]
Hi,
Thanks for letting me know! That's great.

Best,
Shany Ofaim, PhD
Postdoctoral Research Associate
Barabasi Lab
Center for Complex Network Research
Northeastern University, Boston
“The problem is not the problem. The problem is your attitude about the
problem” ― Captain Jack Sparrow

**Comment by cokelaer** [comment]
Closing. This was probably due to a KEGG update?maintenance indeed. Thanks for reporting anyway and using BioServices. I use the KEGG module very often so always looking for feedbacks of course. best
