### ISSUE TITLE
The mapping utility from Uniprot might be broken.

### ISSUE THREAD

**Issue by MengLiuPurdue** [cokelaer/bioservices#177]
**Hi,**

**When I try to run the following code**

`from bioservices import *`
`u = UniProt()`
`u.mapping("ACC", "KEGG_ID", 'P43403')`

**The returned object looks very weird.**

`defaultdict(<class 'list'>, {'SYSTEM': ['"about:legacy-compat">'], '<html': ['xmlns="http://www.w3.org/1999/xhtml"'], 'lang="en"': ['xml:lang="en"><head><title>Retrieve/ID'], 'mapping</title><meta': ['content="IE=edge"'], 'http-equiv="X-UA-Compatible"/><meta': ['content="text/html;'], 'charset=UTF-8"': ['http-equiv="Content-Type"/><meta'], 'content="width=device-width,': ['initial-scale=1"'], 'name="viewport"/><link': ['href="/"'], 'rel="home"/><link': ['href="https://creativecommons.org/licenses/by/4.0/"'], 'rel="license"/><link': ['type="image/vnd.microsoft.icon"'], 'href="/favicon.ico"': ['rel="shortcut'], 'icon"/><link': ['href="/uniprot.min.css2020_04"'], 'type="text/css"': ['rel="stylesheet"/><link'], 'href="/tippy.css"': ['type="text/css"'], 'rel="stylesheet"/><script': ['type="text/javascript">'], 'var': ['BASE'], '=': ["'/';", "'2020_04';"], '</script><script': ['src="/js-compr.js2020_04"', 'type="text/javascript">'], 'type="text/javascript"></script><script': ['src="/scripts/frontier/d3/d3.v5.min.js"', 'type="text/javascript">'], 'uniprot.namespace': ['='], "'uniprot';": ['uniprot.releasedate'], ';': ['</script><meta'], 'content="nositelinkssearchbox"': ['name="google"/></head><body'], 'class="namespace-mapping"': ['typeof="WebPage"'], 'prefix="up:': ['http://purl.uniprot.org/core/"'], 'vocab="http://schema.org/"><span': ['id="evidenceToolTip"'], 'style="display:none">&#xd;': ['&lt;p>An'], 'evidence': ['describes'], 'the': ['source', 'options', 'UniProt', 'features', 'following:', 'identifier', '<i>Submit</i>'], 'of': ['an', 'local', 'peptides', 'this', 'identifiers', 'a'], 'annotation,': ['e.g.'], 'an': ['experiment', 'orthologous', 'external'], 'that': ['has'], 'been': ['published'], 'in': ['the', 'a'], 'scientific': ['literature,'], 'protein,': ['a'], 'record': ['from'], 'another': ['database,'], 'etc.&lt;/p>&#xd;': ['&#xd;'], '&lt;p>&lt;a': ['href="/manual/evidences">More...&lt;/a>&lt;/p>&#xd;'], '</span><p': ['style="display:none"><a'], 'accesskey="2"': ['href="#content">Skip'], 'Header</a></p><div': ['id="masthead-container"><div'], 'class="masthead"': ['id="local-masthead"><div'], 'id="local-title"><a': ['id="logo"'], 'accesskey="1"': ['href="/"><img'], 'alt=""': ['src="/images/logos/Logo_medium.png"'], 'title="UniProt': ['home"/></a></div><div'], 'class="namespace-uniprot"': ['id="local-search"><form'], 'method="get"': ['action="/uniprot"'], 'id="search-form"><div': ['id="namespace-background"><div'], 'class="searchBoxIndicator"': ['style="display:none"'], 'id="searchBoxIndicator1">': ['</div><div'], 'onclick="location.href=&apos;/help/text-search&apos;;"': ['class="searchBoxIndicator"'], 'style="display:none"': ['id="searchBoxIndicator2">', 'id="searchBoxIndicator3">', 'class="select-namespace-options"><a', 'id="basket"><a', 'id="basket-count">0</span></a></div><div', 'id="loadingBasketContent"></div><div', 'class="advanced-search-inputs"><label>Organism'], '</div><div': ['onclick="location.href=&apos;/help/advanced_search', 'id="organismAutoComplete"'], '&apos;;"': ['class="searchBoxIndicator"'], '</div><a': ['class="namespace-select"'], 'id="select-namespace"': ['onclick="return'], 'false;"': ['href=""><span'], 'class="caret_white"': ['id="selected-namespace">UniProtKB</span></a><ul'], 'href="#"': ['class="closeBox"', 'id="uniparc">UniParc</a></h3><p>Sequence', 'id="proteomes">Proteomes</a></h3><p>Protein', 'id="unirule">UniRule', 'id="citations">Literature', 'id="database">Cross-referenced', 'id="advanced-search-toggle">Advanced</a><input', 'class="closeBox"', 'data-icon="b"', 'id="upload-clear"'], 'id="closeNamespaceOptions">x</a><li><ul><li': ['class="fixedHeight_namespaces"><h3'], 'class="namespace_uniprot"><a': ['class="namespace-option'], 'uniprot"': ['href="#"'], 'id="uniprot">UniProtKB</a></h3><p>Protein': ['knowledgebase</p></li><li'], 'class="fixedHeight_namespaces"><h3': ['class="namespace_uniparc"><a', 'class="namespace_proteomes"><a', 'class="supporting"><span>Supporting'], 'class="namespace-option': ['uniparc"', 'proteomes"', 'supporting"', 'supporting"', 'supporting"'], 'archive</p></li><li': ['class="fixedHeight_namespaces"><h3'], 'class="namespace_help"><a': ['class="namespace-option'], 'help"': ['href="#"'], 'id="help">Help</a></h3><p>Help': ['pages,'], 'FAQs,': ['UniProtKB'], 'manual,': ['documents,'], 'news': ['archive'], 'and': ['Biocuration', 'download', 'click', 'click', 'view', 'Innovation</span><span'], 'projects.</p></li></ul></li><li><ul><li': ['class="fixedHeight_namespaces"><h3'], 'class="namespace_uniref"><a': ['class="namespace-option'], 'uniref"': ['href="#"'], 'id="uniref">UniRef</a></h3><p>Sequence': ['clusters</p></li><li'], 'sets': ['from'], 'fully': ['sequenced'], 'genomes</p></li><li': ['class="fixedHeight_namespaces"><h3'], 'class="namespace_unirule">Annotation': ['systems</h3><p'], 'class="supportingLeadingText">Systems': ['used'], 'to': ['automatically', 'map', 'find', 'do', 'UniProt', 'convert', 'another', 'basket"', 'create', 'run', 'inform'], 'annotate': ['proteins'], 'with': ['high', 'the', 'them'], 'accuracy:</p><ul': ['class="supportingDataOptions"><li><a'], '(Expertly': ['curated'], 'rules)</a></li><li><a': ['class="namespace-option'], 'supporting"': ['href="#"', 'href="#"', 'href="#"', 'href="#"', 'href="#"'], 'id="arba">ARBA': ['(System'], 'generated': ['rules)</a></li></ul></li></ul></li><li><ul><li'], 'data</span></h3><p': ['class="supportingLeadingText">Select'], 'one': ['of', 'of'], 'below': ['to'], 'target': ['your', 'type'], 'search:</p><ul': ['class="supportingDataOptions"><li><a'], 'citations</a></li><li><a': ['class="namespace-option'], 'id="taxonomy">Taxonomy</a></li><li><a': ['class="namespace-option'], 'id="keywords">Keywords</a></li><li><a': ['class="namespace-option'], 'id="locations">Subcellular': ['locations</a></li><li><a'], 'databases</a></li><li><a': ['class="namespace-option'], 'id="diseases">Human': ['diseases</a></li></ul></li></ul></li></ul><input'], 'value=""': ['id="topQuery"', 'name="matrix"', 'id="basket-blastQuery"', 'name="jobId"'], 'type="hidden"/><div': ['id="queryContainer"><input'], 'autocomplete="off"': ['autofocus="autofocus"'], 'id="query"': ['value=""'], 'accesskey="4"': ['name="query"'], 'type="search"/></div><a': ['class="caret_grey"'], 'value="score"': ['name="sort"'], 'type="hidden"/><a': ['id="search-button"'], 'title="Search"': ['data-icon="1"'], 'class="icon': ['icon-functional', 'icon-generic', 'icon-functional', 'icon-generic"', 'icon-functional'], 'button">Search</a><div': ['style="display:none"'], 'class="advSearch"': ['id="query-builder-container"><a'], 'id="closeAdvanceSearch">x</a><div': ['id="advanced-search"></div></div></div></form></div><div'], 'id="nav"><ul': ['id="local-nav"><li'], 'class="mobileHomeLink"><a': ['href="/">Home</a></li><li'], 'class="first"><a': ['class="tooltipped"'], 'title="Find': ['regions'], 'similarity': ['between'], 'sequences"': ['href="/blast"'], 'id="top-blast-link">BLAST</a></li><li><a': ['class="tooltipped"'], 'title="Align': ['two'], 'or': ['more', 'to', 'upload', 'work'], 'protein': ['sequences'], 'Clustal': ['Omega'], 'program"': ['href="/align"'], 'accesskey="9"': ['id="top-align-link">Align</a></li><li', 'href="/contact"', 'href="/help/about">UniProt'], 'class="last"><a': ['class="tooltipped"'], 'title="Submit': ['a'], 'list': ['of'], 'identifiers': ['to', 'or'], 'retrieve': ['the'], 'corresponding': ['UniProt', 'UniProt'], 'entries,': ['or'], 'them': ['from'], 'database"': ['rel="help"'], 'href="/uploadlists"': ['id="upload-lists-nav">Retrieve/ID'], 'mapping</a></li><li': ['class="last"><a'], 'class="tooltipped"': ['title="Submit', 'title="Use'], 'a': ['list', 'list', 'BLAST'], 'UniProt': ['sequences', 'proteins,'], 'containing': ['them"'], 'rel="help"': ['href="/peptidesearch"', 'href="/help/"'], 'id="peptidesearch-lists-nav">Peptide': ['search</a></li><li'], 'id="sparql-list"': ['class="last"><a'], 'Kowledge': ['Graph'], 'using': ['SPARQL"', 'a'], 'href="https://sparql.uniprot.org/sparql"': ['id="sparql-lists-nav">SPARQL</a></li><li'], 'class="functional': ['last"><a'], 'id="contact">Contact</a></li><li': ['class="functional"><a'], 'id="help">Help</a></li></ul></div></div></div><div': ['class="warn"'], 'id="browserwarning">You': ['are'], 'version': ['of'], 'browser': ['that'], 'may': ['not'], 'display': ['all'], 'website.': ['Please'], 'consider': ['upgrading'], '<a': ['href="/help/browser_support">your', 'href="/help/license">License', 'href="https://www.uniprot.org/help/about">funding</a>', 'href="/help/privacy">Privacy'], 'browser</a>.</div><main': ['class="mapping"'], 'property="schema:mainEntity"': ['resource=""'], 'typeof=""': ['id="content"><section'], 'id="page-header"><h2': ['class="page-title">Retrieve/ID'], 'mapping</h2><div': ['style="display:none"'], 'class="helpcontent"': ['id="help-mapping"><button'], 'class="closeBox"': ['id="closeHelp">x</button><div'], 'class="helpBoxContainer"><div': ['class="helpBoxPanel'], 'subheading"><h5>How': ['to'], 'use': ['Retrieve/ID', 'the'], 'mapping': ['tool</h5></div><div'], 'class="helpBoxPanel">': ['Enter'], '<ul><li>Retrieve': ['the'], 'entries': ['to'], 'download': ['them'], 'on': ['this', '"Add'], 'website.</li><li>Convert': ['identifiers'], 'which': ['are'], 'different': ['type'], 'vice': ['versa'], 'lists.</li></ul></div></div><div': ['class="helpBoxContainer"><div'], 'class="helpBoxPanel"><ol><li>Enter': ['identifiers,'], 'separated': ['by'], 'spaces': ['or'], 'new': ['lines,', 'window.</label></div></div></div><div><h3>2.'], 'into': ['the'], 'form': ['field,'], 'for': ['example:'], '<div': ['class="indent">', 'class="main"><form'], 'P31946': ['P62258<br/>', 'P62258'], 'ALBU_HUMAN<br/>': ['EFTU_ECOLI<br/></div></li><li>If'], 'you': ['need', 'can', 'can', 'that'], 'identifier': ['type,'], 'select': ['the'], 'source': ['and'], 'from': ['the'], 'dropdown': ['menus.</li><li>Click'], 'button.</li></ol></div><div': ['class="helpLinks"><a'], 'data-icon="?"': ['class="icon'], 'icon-generic': ['namespaceIcons"', 'namespaceIcons"'], 'href="/help/mapping">Help</a><a': ['data-icon="V"'], 'namespaceIcons"': ['target="_blank"', 'href="/downloads">Downloads</a></div></div></div><div'], 'href="https://www.youtube.com/watch?v=kLdgjqWoMZc">Help': ['video</a><a'], 'data-icon="V"': ['class="icon'], 'target="_blank"': ['href="https://www.youtube.com/channel/UCkCR5RJZCZZoVTQzTYY92aw">Other'], 'tutorials': ['and'], 'videos</a><a': ['data-icon="="'], 'id="top-right-actions"><a': ['data-icon="?"'], 'id="showHelp">About': ['</a><div'], 'class="closed': ['basket-empty'], 'icon': ['icon-static', 'icon-functional'], 'caret_white': ['button"'], 'id="basket-list">Basket': ['<span'], 'style="z-index:': ['3;display:none"'], 'id="basket-contents"><div': ['id="closeBasket"><span'], 'class="basketText">(max': ['400'], 'entries)</span><button': ['class="closeBox">x</button></div><div'], 'id="emptyBasketContent"><h3><span': ['class="context-help'], 'tooltipped-click">': ['Your'], 'basket': ['is'], 'currently': ['empty.'], '<sup>': ['i</sup><span'], 'style="display:none"><span': ['class="toolTipContent">'], '&lt;p>When': ['browsing'], 'through': ['different'], "'basket'": ['to'], 'save': ['them,'], 'so': ['that'], 'back': ['to'], 'find': ['or'], 'analyse': ['them'], 'later.&lt;p>&lt;a': ["href='/help/basket'"], "target='_top'>More...&lt;/a>&lt;/p></span></span></span></h3><p>Select": ['item(s)'], 'your': ['own', 'list'], 'collection': ['here<br/>'], '(400': ['entries'], 'max)<br/></p><div': ['id="emptyBasketContentHelp"></div></div><div'], 'id="filledBasketContents"><ul': ['id="basketTabs"'], 'class="tabs"><li><a': ['id="uniprotBasketTab"'], 'class="uniprot': ['tab'], 'basketTab">UniProtKB': ['(<span'], 'class="uniprot-basket-count">0</span>)</a></li><li><a': ['id="unirefBasketTab"'], 'class="uniref': ['tab'], 'basketTab">UniRef': ['(<span'], 'class="uniref-basket-count">0</span>)</a></li><li><a': ['id="uniparcBasketTab"'], 'class="uniparc': ['tab'], 'basketTab">UniParc': ['(<span'], 'class="uniparc-basket-count">0</span>)</a></li></ul><div': ['class="tabsContent"'], 'style="display:': ['none"', 'none"', 'none"'], 'id="basket-uniprot"></div><div': ['class="tabsContent"'], 'id="basket-uniref"></div><div': ['class="tabsContent"'], 'id="basket-uniparc"></div></div><div': ['id="basket-actions"><div'], 'class="action-buttons-grouped"><button': ['title="Select'], 'two': ['or'], 'more': ['entries'], 'here': ['to'], 'align': ['them"', 'disabled"'], 'data-icon="i"': ['class="button'], 'id="basket-align-button">Align</button><button': ['data-icon="t"'], 'title="Select': ['an'], 'entry': ['and'], 'click': ['here'], 'search': ['on'], 'it"': ['class="button'], 'icon-functional': ['icon', 'download'], 'blast': ['disabled"'], 'id="basket-blast-button">BLAST</button><button': ['title="Map'], 'ids': ['to'], 'other': ['databases"'], 'class="button': ['icon-functional', 'icon'], 'disabled"': ['id="basket-map-button">Map', 'id="basket-download-button">Download</button><span'], 'Ids</button><button': ['data-icon="="'], 'title="Download': ['results"'], 'class="icon-right"><button': ['title="Full'], 'View"': ['class="button'], 'fullView': ['disabled"'], 'id="basket-view-button">Full': ['View</button><button'], 'title="Remove': ['Selected'], 'entries"': ['class="button'], 'remove': ['disabled"'], 'id="basket-remove-button">Remove</button><button': ['title="Clear'], 'basket"': ['class="button'], 'clear': ['disabled"'], 'id="basket-clear-button">Clear</button></span></div></div></div><form': ['action="/align/"'], 'method="post"': ['id="basket-alignForm"><input', 'id="basket-blastForm"><input'], 'value="no"': ['name="landingPage"'], 'type="hidden"/><input': ['value="clustalo"', 'value=""', 'value="no"', 'value="10"', 'value="false"', 'value="250"'], 'name="program"': ['type="hidden"/><input'], 'value="yes"': ['name="redirect"', 'name="redirect"'], 'name="alignQuery"': ['id="basket-alignQuery"'], 'type="hidden"/></form><form': ['action="/blast/"'], 'name="landingPage"': ['type="hidden"/><input'], 'value="uniprotkb_refprotswissprot"': ['name="dataset"'], 'name="threshold"': ['type="hidden"/><input'], 'name="filter"': ['type="hidden"/><input'], 'value="true"': ['name="gapped"'], 'name="numal"': ['type="hidden"/><input'], 'name="blastQuery"': ['type="hidden"/></form><form'], 'action=""': ['method="post"'], 'id="basket-downloadForm"><input': ['value=""'], 'name="query"': ['type="hidden"/></form></div></section>'], 'enctype="multipart/form-data"': ['method="post"'], 'url="/uploadlists/"': ['action="/uploadlists/"'], 'id="mapping-form"><input': ['type="hidden"'], 'value="false"': ['name="landingPage"/><div><h3>1.'], 'Provide': ['your'], 'identifiers</h3><div><div': ['class="uploadListsInputboxx"><input'], 'type="hidden"/><textarea': ['placeholder="e.g.'], 'ALBU_HUMAN': ['EFTU_ECOLI"'], 'id="uploadQuery"': ['name="uploadQuery"'], 'class="queryInput': ['uploadListsTextarea'], 'sequence-textarea"></textarea><input': ['type="text"'], 'name="url2"': ['style="display:none"'], '/><div': ['class="uploadFilex"><strong>OR</strong>'], 'upload': ['your'], 'own': ['file:'], '<input': ['id="uploadfile"', 'name="taxon"'], 'name="file"': ['class="uploadList"'], 'type="file"/><span': ['style="display:none"'], 'id="fileNamePlaceHolder"><span': ['data-icon="x"'], 'tooltipped"': ['title="Clear'], 'file': ['uploading"'], 'id="fileUploadCross">': ['</span></span></div><input'], 'id="newTabCheckbox"': ['name="newTabCheckbox"'], 'type="checkbox"/><label': ['for="newTabCheckbox">Run'], 'Select': ['options</h3><div'], 'class="uploadDatabaseSelect"><div': ['id="fromDatabase"'], 'class="advanced-search-inputs">': ['</div><div'], 'id="toDatabase"': ['class="advanced-search-inputs">'], 'id="taxon"></input></label><div': ['id="taxsuggestiontree"'], 'class="tree-select-menu"><div': ['class="tree-select"><ul/></div></div></div></div></div><button'], 'title=""': ['class="button"'], 'type="clear">Clear</button><button': ['title="Upload'], 'results"': ['class="button'], 'go': ['tooltipped"'], 'href=""': ['id="upload-submit"'], 'type="submit">Submit</button></form></div></main><footer': ['id="page-footer"><section><h5>Tools</h5><ul><li><a'], 'href="/blast">BLAST</a></li><li><a': ['href="/align">Align</a></li><li><a'], 'href="/uploadlists">Retrieve/ID': ['mapping</a></li><li><a'], 'href="/peptidesearch">Peptide': ['search</a></li></ul></section><section><h5>Core'], 'data</h5><ul><li><a': ['href="/uniprot">Protein'], 'knowledgebase': ['(UniProtKB)</a></li><li><a'], 'href="/uniref">Sequence': ['clusters'], '(UniRef)</a></li><li><a': ['href="/uniparc">Sequence'], 'archive': ['(UniParc)</a></li><li><a'], 'href="/proteomes">Proteomes</a></li></ul></section><section><h5>Supporting': ['data</h5><ul><li><a'], 'href="/citations">Literature': ['citations</a></li><li><a'], 'href="/taxonomy">Taxonomy</a></li><li><a': ['href="/keywords">Keywords</a></li><li><a'], 'href="/locations">Subcellular': ['locations</a></li><li><a'], 'href="/database">Cross-referenced': ['databases</a></li><li><a'], 'href="/diseases">Diseases</a></li></ul></section><section><h5>Information</h5><ul><li><a': ['href="/help/about">About'], 'UniProt</a></li><li><a': ['href="/help">Help</a></li><li><a'], 'href="/help/?fil=section:faq">FAQ</a></li><li><a': ['href="/help/?fil=section:manual">UniProtKB'], 'manual</a></li><li><a': ['href="/help/technical">Technical'], 'corner</a></li><li><a': ['href="/help/?query=*&amp;fil=section:biocuration">Expert'], 'biocuration</a></li></ul></section><section><div': ['class="uniprotlogo"><img'], 'src="/images/logos/uniprot-rgb-optimized.svg"/></div><span>&copy;': ['2002'], '&ndash;': ['<span'], 'property="copyrightYear">2020</span>': ['<a'], 'Consortium</a>': ['|'], '&amp;': ['Disclaimer</a>'], '|': ['<a'], 'href="/help/privacy">Privacy': ['Notice</a></span><div'], 'resource="/help/about#UniProt"': ['id="logos"'], 'typeof="NGO"': ['property="creator"><span'], 'hidden="hidden"': ['property="name">UniProt', 'property="name">The', 'property="name">State', 'property="alternateName">SERI</span></a></div><script'], 'Consortium</span><span': ['resource="/help/about#EBI"'], 'typeof="Organization"': ['class="ebi"', 'class="pir"', 'class="sib"', 'href="https://www.coretrustseal.org/"', 'href="https://www.elixir-europe.org/platforms/data/core-data-resources"', 'href="https://www.embl.org/"'], 'property="member"><span': ['class="hidden"', 'class="hidden"', 'class="hidden"'], 'property="name">European': ['Bioinformatics'], 'Institute</span><a': ['href="https://www.ebi.ac.uk/"'], 'property="url"></a></span><span': ['resource="/help/about#PIR"', 'resource="/help/about#SIB"'], 'property="name">Protein': ['Information'], 'Resource</span><a': ['href="https://pir.georgetown.edu/"'], 'property="name">SIB': ['Swiss'], 'Institute': ['of'], 'Bioinformatics</span><a': ['href="https://www.sib.swiss/"'], 'property="url"></a></span></div></section></footer><div': ['id="elixir-coretrust-ribbon"><a'], 'property="reviewedBy"><img': ['alt="UniProt', 'height="64px"'], 'is': ['an', 'an'], 'CoreTrustSeal': ['certified'], 'data': ['repository"', 'resource</span></h5></a></div><div'], 'id="coretrustseal-logo"': ['src="/images/logos/CoreTrustSeal-logo-transparent.png"/></a><a'], 'width="64px"': ['id="elixir-cdr-logo"'], 'src="/images/elixir-cdr.gif"/><h5><span': ['class="elixir-banner-name">UniProt'], 'ELIXIR': ['core'], 'id="UniProt-Funding"><span>': ['Main'], 'by:': ['</span><a'], 'property="funder"': ['typeof="Organization"', 'typeof="GovernmentOrganization"'], 'href="https://www.nih.gov/"': ['id="nihFundingLink"'], 'class="funder"><span': ['property="name">National'], 'Institutes': ['of'], 'Health</span></a><a': ['property="funder"'], 'id="ebiFundingLink"': ['class="funder"><img'], 'src="/images/embl-logo.png"': ['style="width:auto;height:45px;"/><span'], 'European': ['Molecular'], 'Biology': ['Laboratory</span></a><a'], 'href="https://www.sbfi.admin.ch/sbfi/en/home.html"': ['id="seriFundingLink"'], 'class="funder"><img': ['src="/images/seri-logo.png"/><span'], 'Secretariat': ['for'], 'Education,': ['Research'], 'src="https://www.google-analytics.com/analytics.js"': ['async="async"></script><script>'], 'window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new': ['Date;'], "ga('create',": ["'UA-6228219-1',"], "'auto');": ["ga('set',"], "'anonymizeIp',": ['true);'], "ga('set',": ["'forceSSL',"], 'true);': ["ga('send',"], "'pageview');": ['</script><div'], 'class="privacy-panel"': ['id="privacy-panel"><p'], 'class="privacy-panel__text">We\'d': ['like'], 'we': ['have'], 'updated': ['our'], 'Notice</a>': ['to'], 'comply': ['with'], 'Europe’s': ['new'], 'General': ['Data'], 'Protection': ['Regulation'], '(GDPR)': ['that'], 'applies': ['since'], '25': ['May'], '2018.</p><a': ['id="privacy-panel-accept"'], 'class="privacy-panel__button">Do': ['not'], 'show': ['this'], 'banner': ['again</a></div><script'], 'src="/scripts/node-bundle.js"': ['type="text/javascript"></script><script'], 'src="/scripts/common-bundle.js"': ['type="text/javascript"></script><script'], 'src="/scripts/upload-bundle.js"': ['type="text/javascript"></script></body></html>']})`

**Comment by cokelaer** [comment]
This works for me. Unfortunately, this is a recurring issue and it related to the underlying services that may be slow or down from time to time:

    from bioservices import * 
    u = UniProt() 
    u.mapping("ACC", "KEGG_ID", 'P43403')                                                                        

return

    defaultdict(list, {'P43403': ['hsa:7535']})
