### ISSUE TITLE
Get the reaction_mapformula.lst file from KEGG

### ISSUE THREAD

**Issue by yut8920** [cokelaer/bioservices#181]
Dear all,

I want to get the reversibility of reactions from KEGG.I get all reactions information via bioservices, but there's no information about reversibility. I find the reaction_mapformula.lst file contains the reversibility of each reaction. Thus, I wonder how to get the file through bioservices.

Thank you.

**Comment by cokelaer** [comment]
@yut8920 
I would need a little help here. I am not familiar with this mapformula.list file or reversibility of reactions. Would have example and maybe more insights into what you wish to achieve ? thanks

**Comment by yut8920** [comment]
[reaction_mapformula.txt](https://github.com/cokelaer/bioservices/files/5581855/reaction_mapformula.txt)
Thank you for your attention. This is the file I want, but I do not have the latest edition.

**Comment by yut8920** [comment]
@cokelaer 
Thank you for your attention.This is the file I want, but I do not have the latest edition. I hope that will be helpful.
[reaction_mapformula.txt](https://github.com/cokelaer/bioservices/files/5581884/reaction_mapformula.txt)

**Comment by cokelaer** [comment]
First ,from the KEGG class you can get all reactions as follows:

    from bioservices import KEGG
    k = KEGG()
    reactions = k.reactionIds

Then, you can get and parse into a useful dictionary each reaction. For example for the fourth reaction in the list (corresponding to R00005):

    k.parse(k.get(k.reactions[3]))

You should see something like::

    {'ENTRY': 'R00005                      Reaction',
     'NAME': ['urea-1-carboxylate amidohydrolase'],
     'DEFINITION': 'Urea-1-carboxylate + H2O <=> 2 CO2 + 2 Ammonia',
     'EQUATION': 'C01010 + C00001 <=> 2 C00011 + 2 C00014',
     'COMMENT': ['The yeast enzyme (but not that from green algae) also catalyses the',
      'reaction of EC 6.3.4.6 urea carboxylase, thus bringing about the',
      'hydrolysis of urea to CO2 and NH3 in the presence of ATP and',
      'bicarbonate.',
      'R00774 (6.3.4.6)'],
     'RCLASS': 'RC02756  C00011_C01010',
     'ENZYME': ['3.5.1.54'],
     'PATHWAY': {'rn00220': 'Arginine biosynthesis',
      'rn00791': 'Atrazine degradation',
      'rn01100': 'Metabolic pathways',
      'rn01120': 'Microbial metabolism in diverse environments'},
     'ORTHOLOGY': {'K01457': 'allophanate hydrolase [EC:3.5.1.54]',
      'K14541': 'urea carboxylase / allophanate hydrolase [EC:6.3.4.6 3.5.1.54]'},
     'DBLINKS': {'RHEA': '19032'}}

You are interested in the keys PATHWAY and EQUATION.

To generate your reaction_mapformula.txt, this code should work. 

    for reaction in reactions:
        data = k.parse(k.get(reaction))
        if 'PATHWAY' in data.keys():
            for pathway in sorted(data['PATHWAY'].keys()):
                print("{}: {}: {}".format(reaction, pathway, data['EQUATION']))

Note that equation for R00005 (for example) differs from yours. Not sure what this means. So use with care. I believe this answer to your question.

**Comment by yut8920** [comment]
@cokelaer 
In fact, I am interested in the actual  direction of the reaction in the pathway. Such as R00005, we can get the PATHWAY and EQUATION information through your method. Since the reactants and products are connected by the '<=>' , we assume that the reaction is reversible. However, the actual direction is from C01010 to C00011 in the pathway by checking it in KEGG database.This is the problem what I want to solve.
![image](https://user-images.githubusercontent.com/49741074/101300058-395f3c00-386f-11eb-8684-8ea5d1e50b6b.png)

**Comment by cokelaer** [comment]
@yut8920 not sure we can solve that given the information in the reaction structure of KEGG database. This is clearly not in the reaction itself. It looks like you can see the direction from the kegg pathway image. Although we can have the direction in signalling pathways, in the example above for r00005, looking e.g. at the reaction pathway rn00220, no informaton about direction are provided. I do not see any way to have this information for now except assuming that the order in the reaction itself is the one used in the pathway.
