### ISSUE TITLE
Found keyword NETWORK, which has not special  parsing for now

### ISSUE THREAD

**Issue by bhwl12** [cokelaer/bioservices#182]
WARNING [bioservices:keggparser]:  Found keyword NETWORK, which has not special
 parsing for now. please report this issue with the KEGG 
identifier (5515              CDS       T01001) into github.com/bioservices. Thanks T.C.
WARNING [bioservices:keggparser]:  Could not fully interpret DRUG_TARGET

Thanks!

**Comment by cokelaer** [comment]
Fixed on the main master branch. Will be included in future release coming in the next few days on pypi
