### ISSUE TITLE
Always get WARNING [bioservices:UniProt]: column could not be parsed. Subcellular location

### ISSUE THREAD

**Issue by joaquinabian** [cokelaer/bioservices#183]
```
from bioservices import uniprot
u = uniprot.UniProt()
df = u.get_df(['A9UMV8'])
```
Or any other searched accession produces (maybe) always: 
`WARNING [bioservices:UniProt]:  column could not be parsed. Subcellular location`

win10 64bit
python 3.8.6
jupyter notebook server 6.1.5

**Comment by cokelaer** [comment]
Should be fixed in latest version of bioservices
