### ISSUE TITLE
need a workaround for PSICQUIC in biogrid queries

### ISSUE THREAD

**Issue by mkarikom** [cokelaer/bioservices#184]
just the example from [the docs](https://bioservices.readthedocs.io/en/master/references.html?highlight=biogrid#module-bioservices.biogrid):
```
b = bg(query=["map2k4","akt1"],taxId = '10090')
WARNING [bioservices:PSICQUIC]:  The URL (http://www.ebi.ac.uk/Tools/webservices/psicquic) provided cannot be reached.
```
What is the reason for this requirement that PSICQUIC be reachable?

EBI web services don't have a great track record for reliability (sometimes they [just go dark permanently](https://www.ebi.ac.uk/rdf/documentation/sparql-endpoints/)).   Better to use NCBI or SIB.

**Comment by cokelaer** [comment]
This is just a warning, which is annoying indeed but has no impact. This should be removed in new version 1.7.11 soon online.

**Comment by mkarikom** [comment]
ok thanks!
