### ISSUE TITLE
Psicquic : RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by OcMalde** [cokelaer/bioservices#189]
https://github.com/cokelaer/bioservices/blob/cec2fe348739ec93287fe749a1e10b5c27f7d9df/src/bioservices/psicquic.py#L694

Created an issue when called by ; 
```p.queryAll("NP_001307265.1 AND species:9606", databases=db_list)```

=> RuntimeError: dictionary changed size during iteration

Fix proposed : iterate on a copy instead ot the query.keys()

replace psicquic.py L694 ```for k in query.keys():```
with ```for k in list(query.keys()):```

**Comment by cokelaer** [comment]
Fixed on the main branch for now and will be add to next release. Thanks for reporting this issue
