### ISSUE TITLE
bioservices fails to import in Python 3.3.3 due to gevent

### ISSUE THREAD

**Issue by ricosaurus** [cokelaer/bioservices#19]
Looks like a useful project for xref genes/proteins!

I can successfully install in Python 2.7.8, but in Python 3.3.3, after pip install bioservices (with some complaining about gevent, but supposed success) on import:

In [1]: import bioservices
  File "/home/richard/venv3.3/lib/python3.3/site-packages/gevent/hub.py", line 282
    except Exception, ex:
                    ^
SyntaxError: invalid syntax

From google it seems gevent is not Py3k compatible.  Is there a forked version I am missing?

**Comment by cokelaer** [comment]
BioServices is now compatible with python 3.3.5 and 3.4.2 (travis success). Won't be maintained for 3.3.3 but it may work now.
