### ISSUE TITLE
bioservices 1.7.12 not on Conda

### ISSUE THREAD

**Issue by a-r-j** [cokelaer/bioservices#190]
Latest version on conda is 1.7.11 which throws some errors related to colorlog.

**Comment by cokelaer** [comment]
@a-r-j  thanks for reporting the issue. 

I'm not sure what to do for now. Bioservices was on bioconda and has been moveed recently to conda-forge itself: https://github.com/conda-forge/bioservices-feedstock  A new version 1.8.0 will most probably be released soon. I had a go with versio 1.7.12 using 

     conda create --name bioservices python=3.7
     conda activate bioservices
      conda install -c conda-forge bioservices

**Comment by cokelaer** [comment]
Looks like it is indeed on conda-forge now. Release 1.7.12 is available on conda-forge.

**Comment by a-r-j** [comment]
Good news! Thanks for a great project btw :)
