### ISSUE TITLE
batch sequences export

### ISSUE THREAD

**Issue by sailseem** [cokelaer/bioservices#191]
Dear developer,
  Can i export multiple sequences by input a list of unipor ID in txt files?
something like this in a batch way.
sequence = u.retrieve("P43403", "fast")

Thanks

**Comment by cokelaer** [comment]
Dear @sailseem ,
Yes, indeed, from the documentation  (u.retrieve? in a python shell), you can use:

    u.retrieve(['P29317', 'Q5BKX8', 'Q8TCD6'], frmt='fasta')
    
Each fasta will be present with its identifier.
