### ISSUE TITLE
Migrate from suds-jurko to suds-community dependency

### ISSUE THREAD

**Issue by a-r-j** [cokelaer/bioservices#192]
Suds-jurko is no longer maintained: https://issueexplorer.com/issue/pypa/setuptools/2784

Should be switched out for: https://github.com/suds-community/suds/blob/master/README.md

**Comment by cokelaer** [comment]
Thanks for the suggestions. This is now integrated

**Comment by harper357** [comment]
Shouldn't https://github.com/cokelaer/bioservices/blob/b9d98af52dfe64268dd02d9edc2edec85a83befe/setup.py#L61 
and 
https://github.com/cokelaer/bioservices/blob/b9d98af52dfe64268dd02d9edc2edec85a83befe/requirements.txt#L10
be changed to `suds-community`?
