### ISSUE TITLE
Problem importing bioservices

### ISSUE THREAD

**Issue by Benfeitas** [cokelaer/bioservices#197]
Hi,

I'm running bioservices 1.8.2 in a conda environment, under python 3.7.12. When I simply try to import it it fails:

```
>>> import bioservices
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/vh/twxllthj78j2bww9v4p_hjx1f3blpf/T/ipykernel_30204/975526758.py in <module>
----> 1 import bioservices

~/opt/miniconda3/envs/my_conda_env/site-packages/bioservices/__init__.py in <module>
     38 from .settings import *
     39 
---> 40 from . import services
     41 from .services import *
     42 

~/opt/miniconda3/envs/my_conda_env/site-packages/bioservices/services.py in <module>
     37 
     38 # fixing compatibility issue of input/raw_input
---> 39 if "raw_input" in __builtins__:
     40     input = raw_input
     41 

TypeError: 'module' object is not iterable
```

I have tried:
- Installing different versions of bioservices from `bioconda` and `conda-forge`;
- Installing bioservices with `pip install bioservices`
- Installing bioservices 1.7.10, 1.7.11, 1.8.2

Any suggestions on how to solve this?

**Comment by cokelaer** [comment]
@benfeitas 

Really sorry that you face this issue. I do not know. It should work out of the box... I am using 3.7.3 for instance. THere are continuous integration for 3.7 ,3.8, 3.9 

Now, saying that, it does not help... maybe there is a conflicting version of bioservices ? I know that bioconda moved bioservices to conda-forge recently so I would recommend the conda-forge anyway. 

Have you tried from the source code ?

**Comment by cokelaer** [comment]
Closes due to lack of activity and probably deprecated by now with newer versions
