### ISSUE TITLE
biomodels.get_all_models() hangs

### ISSUE THREAD

**Issue by luciansmith** [cokelaer/bioservices#200]
Following the suggestion at:

https://bioservices.readthedocs.io/en/master/biomodels.html

I ran:

```
models = s.get_all_models()
```

but it took a very very long time to execute; long enough that I couldn't tell if it had hung or not, and just killed the process after several hours.

**Comment by cokelaer** [comment]
Looks like this problem was also found by another user who fixed the issue. Will be fixed in the version 1.8.4 to released today
