### ISSUE TITLE
Unichem api update

### ISSUE THREAD

**Issue by JamesPino** [cokelaer/bioservices#212]
It looks like Unichem has updated their api.

https://chembl.gitbook.io/unichem/unichem-2.0/unichem-2.0-beta/whats-new

Anyone already working on updating to accommodate?

**Comment by cokelaer** [comment]
@JamesPino I've checked the API. I was surprised first because all unichem tests from bioservices are still passing...looks like legacy functions have been kept for now, which is great. So, for the new API, I'll check whether I can do it during the following days. If not, I'll add a comment here.

**Comment by cokelaer** [comment]
@JamesPino unichem new API is now integrated. Finally, the old functions were not working, obviously (a cache problem) so now the new function from unichem are integrated as well as their legacy functions.
