### ISSUE TITLE
new uniprot service to be integrated

### ISSUE THREAD

**Issue by cokelaer** [cokelaer/bioservices#213]
https://beta.uniprot.org/help/api_retrieve_entries

**Comment by DDudka9** [comment]
I started getting Bad Request (code 400) error since June 28th 2022 when using UniProt class as indicated in the documentation. Is there a code update or a suggested workaround?

**Comment by DDudka9** [comment]
I have been using this service virtually every day so Im looking forward for a workaround and super grateful for a quick response!

**Comment by cokelaer** [comment]
@sheljoy uniprot sercice from ebi was changed this week. I have now updated  bioservices to réflect these changes . Bioservices 1.10 is now available on pypi.org and I guess an update on conda forge should be available in a couple of days. Some api changes will required your code to be updated. Everything should be documentéd within the code and online docs on bioservices.readthedocs.io

**Comment by alexbioinf** [comment]
yep, I still have an error message ""The combination of 'from=ID' and 'to=KEGG_ID' parameters is invalid"]" when running a simple
u = UniProt(verbose=False)
u.mapping(fr='ID', to='KEGG_ID', query="P31946")

I guess it is also related to that issue... I have recent bioservices 1.10 installed through pip...

**Comment by cokelaer** [comment]
KEGG_ID should be KEGG. I have now updated the online documentation as well
