### ISSUE TITLE
Found keyword SYMBOL, which has not special parsing for now.

### ISSUE THREAD

**Issue by ginkyenglee** [cokelaer/bioservices#217]
Hi,
I'm running bioservices 1.9.0, under python 3.8.10, and I was trying simple example below
```python
k = KEGG()
k.organism = "hsa"
k.get_pathway_by_gene("7535","hsa")
```

And I receive the following output

```terminal
WARNING [bioservices:keggparser:119]:  Found keyword SYMBOL, which has not special
    parsing for now. please report this issue with the KEGG
    identifier (7535              CDS       T01001) into github.com/bioservices. Thanks T.C.
Pfam  PK_Tyr_Ser-Thr Pkinase SH2 ABC1 Haspin_kinase Kdo
WARNING [bioservices:keggparser:119]:  Could not parse the entry CDS       T01001 correctly
WARNING [bioservices:keggparser:119]:  not enough values to unpack (expected 2, got 1)
```

And I have found very similar issue in #195 but the comment did not help.
I have tried : 

- other gene ids or names with `get_pathway_by_gene` function 
- Installing different versions of bioservices from bioconda;

Thanks for any help!

**Comment by cokelaer** [comment]
@ginkyenglee I am surprised you got that specific reference to the keywor 'SYMBOL' since it is included in the parser of bioservices 1.9.0  

If you type 

    bioservices --version

do you indeed  have v1.9.0 installed ?
