### ISSUE TITLE
uniprot updated!! WARNING [bioservices.UniProt:596]:  status is not ok with Bad Request

### ISSUE THREAD

**Issue by sheljoy** [cokelaer/bioservices#219]
uniprot updated with REST api : https://www.uniprot.org/help/return_fields

```{python}
import bioservices,re
bsup = bioservices.uniprot.UniProt(verbose=True)
bsup.search("Q969J5")
```
WARNING [bioservices.UniProt:596]:  status is not ok with Bad Request
400

**Comment by cokelaer** [comment]
@sheljoy uniprot sercice from ebi was changed this week. I have now updated  bioservices to réflect these changes . Bioservices 1.10 is now available on pypi.org and I guess an update on conda forge should be available in a couple of days
