### ISSUE TITLE
QuickGO Term oboxml format returns HTML format

### ISSUE THREAD

**Issue by Norore** [cokelaer/bioservices#22]
I recently open scripts from a project for my colleagues, began few months ago.
I was surprised that the call format method was changed, but I changed all the impacted scripts.
Now I am confronted to a new trouble. When I send a request to get a GO Term in OBOXML format, bioservices sends me a HTML format. I didn't see anything about this issue on the changelog.

Example:
Get the OBOXML format for the term GO:0000016
```python
from bioservices import QuickGO as qgo
qgo = qgo()
term = qgo.Term("GO:0000016", frmt="oboxml")
print term
```

I checked the source script, by curiosity, and I wonder if the problem could be the parameters (script quickgO.py, line 116, 'frmt' in place of 'format'?)

**Comment by cokelaer** [comment]
Hi, Yes, I changed all 'format' parameters to 'frmt' in all bioservices code in version 1.3.0. So, scripts must be updated indeed. 

I added this changes in the detailled changelog: https://github.com/cokelaer/bioservices/blob/master/doc/source/ChangeLog.rst

I have now updated the short changelog to emphasize that change of API. 

thanks

**Comment by cokelaer** [comment]
I see. There is a typo in the Term method indeed. I'll commit/push the corrected version of quickgo in a moment.
