### ISSUE TITLE
uniprot mapping service does not work

### ISSUE THREAD

**Issue by alexbioinf** [cokelaer/bioservices#223]
a simple examples from tutorial returns either 400 error or "The combination of 'from=ID' and 'to=KEGG_ID' parameters is invalid"

from bioservices.uniprot import UniProt
u = UniProt(verbose=False)
print(u.search("ZAP70 and taxonomy:human", limit=3))
u.mapping(fr='ID', to='KEGG_ID', query="P31946")

**Comment by cokelaer** [comment]
@alexbioinf I have Poor connection at the moment so not sure whether the documentation is outdated or whether it is a bug. Be aware that uni prot API has changed recently. Make sure you have the latest pypi version of bioservices first. Then possibly it is the identifier of kegg and uni prot that have changed in their database. For kegg try to remove the training _ID

**Comment by cokelaer** [comment]
I have now updated the online examples
