### ISSUE TITLE
uniprot ome columns have been dropped or changed

### ISSUE THREAD

**Issue by cokelaer** [cokelaer/bioservices#226]
Looks like these arguments have been dropped:

    WARNING [bioservices.UniProt:837]:  column could not be parsed. protein_families
    WARNING [bioservices.UniProt:837]:  column could not be parsed. Gene names
    WARNING [bioservices.UniProt:837]:  column could not be parsed. go
    WARNING [bioservices.UniProt:837]:  column could not be parsed. go_ids
    WARNING [bioservices.UniProt:837]:  column could not be parsed. interaction
    WARNING [bioservices.UniProt:837]:  column could not be parsed. keyword

**Comment by GianArauz** [comment]
I add another argument to this list:
`WARNING [bioservices.UniProt:838]:  column could not be parsed. lit_pubmed_id`

**Comment by cokelaer** [comment]
@GianArauz thanks again for the PR. Concerning the warnings, they will be removed in the next release of bioservices.
