### ISSUE TITLE
KEGG 'MEMBER' keyword without special parsing & T/nt numbers

### ISSUE THREAD

**Issue by nc1m** [cokelaer/bioservices#233]
Hi,

the following warning appeared while using the library:
`WARNING [bioservices:keggparser:119]:  Found keyword MEMBER, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (DG01245                     DGroup) into github.com/bioservices. Thanks T.C.`

Also the get method does not seem to work with T and nt numbers:
```
kegg = KEGG()  
kegg.get('T01001')  
=> WARNING [bioservices.KEGG:596]:  status is not ok with Bad Request
```
https://www.kegg.jp/entry/T01001
and
```
kegg = KEGG()  
kegg.get('nt06214')  
=> WARNING [bioservices.KEGG:596]:  status is not ok with Not Found
```
https://www.kegg.jp/entry/nt06214

Thanks

**Comment by cokelaer** [comment]
Looks like when using the get method, some entries needs to be annotated. This is the case for T01001, which is a genome, and nt06214, which is a network. So, you must use:

    kegg.get('gn:T01001')
   kegg.get('network:nt06214')

I have updated the documentation that will appear here
https://bioservices.readthedocs.io/en/main/references.html#bioservices.kegg.KEGG.get

**Comment by cokelaer** [comment]
For the network case, you will need a new version (1.10.3) that should be released in a few days

**Comment by nc1m** [comment]
Thanks for the help and your work!
