### ISSUE TITLE
ChEMBL Service cannot be reached

### ISSUE THREAD

**Issue by ItamarChinn** [cokelaer/bioservices#239]
When trying to use the ChEMBL bioservice the following warning is returned:

```
from bioservices import ChEMBL
s = ChEMBL(verbose=False)
WARNING [bioservices.ChEMBL:130]:  The URL (https://www.ebi.ac.uk/chembl/api/data) provided cannot be reached.
```

**Comment by cokelaer** [comment]
@ItamarChinn this is a warning only.
If you try to use the service, e.g.,:

    from bioservices import ChEMBL
    s = ChEMBL(verbose=False)
    s.get_molecule(limit=10)

It should work. I will remove this warning in the future release. thanks anyway for using chembl and reporting this useless warning
