### ISSUE TITLE
pip install gives FileNotFoundError for version 1.10.3

### ISSUE THREAD

**Issue by gildossantos** [cokelaer/bioservices#241]
When I try to upgrade bioservices, I get a FileNotFoundError for the `requirements.txt` file. Seems like the issue is specific to version 1.10.3.

```
$ pip install bioservices==1.10.3
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: bioservices in ./.local/lib/python3.10/site-packages (1.10.2)
Collecting bioservices
  Using cached bioservices-1.10.3.tar.gz (197 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-86ykapt1/bioservices_db107e44da134b10a2d2b30bc9b501f7/setup.py", line 51, in <module>
          with open('requirements.txt', 'r') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by cokelaer** [comment]
@gildossantos what platform are you using / Mac/windows/Linux

**Comment by cokelaer** [comment]
When I create the distribution locally, the file requirements.txt is installed. That's wierd. Wondering whether this is related to the Python version 3.10 you are using. I will add python3.10 in the continuous integration to double check

**Comment by Yuxi987** [comment]
Hi cokelaer,

I am trying to install it on WSL(Ubuntu) with python version 3.8. But I have the same problem.

**Comment by benduc** [comment]
Hi cokelaer,

Same issue on GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21). Python 3.8.

**Comment by gildossantos** [comment]
Hi @cokelaer,
I'm getting this error on my Linux (Ubuntu 22.04.1 LTS) system, as well as in docker (alpine:3.10.2). In both cases, using python 3.10. Thanks.

**Comment by dcnadler** [comment]
Same issue, docker image jupyter/scipy-notebook:latest (python 3.10)
Needed to add
```
bioservices!=1.10.3 
```

**Comment by cokelaer** [comment]
Thanks all for reporting the issue. my bad. Updating the setup had a side effect, not anticipated... I removed the v1.10.3 from pypi, updated the code and the new release 1.10.4 should fix the issue.

**Comment by gildossantos** [comment]
Thanks! Confirming that the new version now works for me.

**Comment by dcnadler** [comment]
Can confirm the bug is fixed for me, too. Thanks for the quick response!

**Comment by benduc** [comment]
Solved on my side also. Thanks!
