### ISSUE TITLE
error in PDBe module or just in the example?

### ISSUE THREAD

**Issue by hrp1000** [cokelaer/bioservices#247]
Using the example on the bioservices web-page - 

from bioservices import PDBe
s = PDBe()
_WARNING [bioservices.PDBe:130]:  The URL (https://www.ebi.ac.uk/pdbe/api/pdb/entry/) provided cannot be reached._
res = s.get_file("1FBV", "pdb")
_Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'PDBe' object has no attribute 'get_file'_

("get_files" exists but is not called in the same way...)

s = PDBe(verbose=True)
_WARNING [bioservices.PDBe:130]:  The URL (https://www.ebi.ac.uk/pdbe/api/pdb/entry/) provided cannot be reached.
INFO    [bioservices.PDBe:363]:  Initialising PDBe service (REST)_

**Comment by cokelaer** [comment]
@hrp1000  indeed this is a typo in the doc. should have been 

    s.get_files('1FBV')

will be fix in the coming release. thanks for reporting this typo.
