### ISSUE TITLE
BioCyc Interface

### ISSUE THREAD

**Issue by mfitzp** [cokelaer/bioservices#28]
It's great to see a multi-service package like this being developed! [I found you via this post here](http://www.reddit.com/r/bioinformatics/comments/2w5f1a/bioservices_python_wrapper_for_many_different/)

I noticed that there isn't an API for [BioCyc](http://biocyc.org/) yet.

I have an implementation of one here [here](https://github.com/mfitzp/biocyc) that uses the Web API to allow browsing of BioCyc objects. See the [example notebook](http://nbviewer.ipython.org/github/mfitzp/ipython-notebooks/blob/master/public/BioCyc%20Interface%20Demo.ipynb) for an example. Improving the API to seamlessly support a local PathwayTools server is on the someday todo list.

Would you be interested in merging this into the bioservices package? It seems a natural fit

**Comment by cokelaer** [comment]
Hi Martin,
Sounds good to me. I'm interested of course to integrate biocyc inside bioservices. 

I'm just thinking about the way to proceed. Usually, people integrate an REST service using bioservices interface starting from scratch but you have already done the work within your repo so I'm not sure what is the best way to proceed. What did you have in mind exactly on the merging ? We could either write a wrapping of the biocyc package inside bioservices, or re-use REST class from bioservices and adapting your code. I would prefer not to have a dependency on biocyc package itself but to rather merge them. What do you think of that ?

**Comment by mfitzp** [comment]
Great! My preference would be to adapt the `biocyc` code to use the bioservices API (basically a re-write). Using some kind of wrapper would probably end up quite ugly and unmaintainable. 

There are a few 'clever' things that the current `biocyc` package does such as caching objects (pickled with expiry) to speed up subsequent calls. Looking at the bioservices package it uses http-caching on requests (via `requests_cache`). How long does the cache persist?

Looking at the other APIs they appear to return string/lists rather than ‘objects’ to represent items returned from the service. It might make sense to implement the BioCyc API to use the same approach (return IDs rather than objects). One possibility would be to implement the bare API in bioservices, then maintain a object-orientated wrapper for it in a separate package (this can also go within bioservices if you like, it depends on your goals for the project).


On 17 February 2015 at 18:37, Thomas Cokelaer <notifications@github.com> wrote:
Hi Martin,
Sounds good to me. I'm interested of course to integrate biocyc inside bioservices.

I'm just thinking about the way to proceed. Usually, people integrate an REST service using bioservices interface starting from scratch but you have already done the work within your repo so I'm not sure what is the best way to proceed. What did you have in mind exactly on the merging ? We could either write a wrapping of the biocyc package inside bioservices, or re-use REST class from bioservices and adapting your code. I would prefer not to have a dependency on biocyc package itself but to rather merge them. What do you think of that ?

**Comment by cokelaer** [comment]
closing ue to inactivity
