### ISSUE TITLE
installation error of bioservices 

### ISSUE THREAD

**Issue by satyausc** [cokelaer/bioservices#31]
Hi, 
I have python2.6 installed on my server (I can not change to new one ). i am getting the following error message during installation 

Extracting bioservices-1.3.5-py2.6.egg to /home/satya/python/lib/python2.6/site-packages
SyntaxError: ('invalid syntax', ('/home/satya/python/lib/python2.6/site-packages/bioservices-1.3.5-py2.6.egg/bioservices/kegg.py', 1569, 50, "                output['dblinks'] = {k[0:-1]:v for k,v in output['dblinks'].items()}\n"))

SyntaxError: ('invalid syntax', ('/home/satya/python/lib/python2.6/site-packages/bioservices-1.3.5-py2.6.egg/bioservices/mapping/mappers.py', 149, 37, "        data = {k1:{k2:v2['xkey'] for k2,v2 in self.alldata[k1].iteritems()} for k1 in self.alldata.keys()}\n"))

Please let me know the fix

**Comment by cokelaer** [comment]
Hello, 

I'm checking bioservices installation under Python 2.7 and 3.3 on Travis for instance https://travis-ci.org/cokelaer/bioservices and generally speaking there is no errors. Unfortunately, I'm not maintening bioservices for python 2.6. I can have a quick look at this particular error but I fear it won't be the only one. 
I keep this bug report open and will have a quick look later today. 

thanks for reporting the error.
best
T.

**Comment by satyausc** [comment]
Thanks Cokelaer, 
I hope you do not run into more errors. I am bound to run it with python2.6 because I am working on server where I can not upgrade to newer version of python.

**Comment by cokelaer** [comment]
BioService is now compatible with python 2.6 and intregrated with travis (tests passed succesfully in version 1.4.1).
