### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by xapple** [cokelaer/bioservices#42]
I just installed bioservices and copy pasted the example code in ipython. It didn't work.

     from bioservices import UniProt
     u = UniProt()
     data = u.search("zap70+and+taxonomy:9606", format="tab", limit=3, columns="entry name,length,id, genes")

Result:

    TypeError: search() got an unexpected keyword argument 'format'

**Comment by cokelaer** [comment]
Hi, 
I need to update the documet. I changed "format" to frmt almost everywhere in the code a while ago but some of the code have not been updated. I will take care of that in the next commits

**Comment by xapple** [comment]
I have no idea why `frmt` would be better than `format`... but I'm just saying you can loose lots of potentially interested users when your first and foremost example doesn't even work.

**Comment by cokelaer** [comment]
just for your information, I decided to use `frmt` to not be in conflict with the python keyword `format` . Not usre this was a good choice but anyway. I have now updated the documentation, notebooks and tests and hopefully the examples and documentation should work. Thanks again for reporting the issue.

**Comment by xapple** [comment]
Awesome ! I hope your library gains traction. It was useful to be for the UniProt API it provides ! And I was able to avoid using urllib2 and dealing with the mess that that brings along.
