### ISSUE TITLE
Taxonomy missing

### ISSUE THREAD

**Issue by xapple** [cokelaer/bioservices#43]
I found an other example in the documentation:

    from bioservices.apps.taxonomy import Taxon

Result:

    ImportError: No module named taxonomy

Using version 1.4.0

**Comment by cokelaer** [comment]
I have moved some contents from bioesrvices.app package into another library called biokit (http://github.com/biokit) . The reason being that Taxon class is not dedicated to a web service and i will try to keep bioservices as  a dedicated library to wrapping of web services and biokit more of a tool box including the Taxon class.
