### ISSUE TITLE
Missing SEQUENCE in KEGGParser

### ISSUE THREAD

**Issue by JamesPino** [cokelaer/bioservices#46]
When parsing multiple kgml files I get the warning saying SEQUENCE is missing. Everything still functions. It happens for kegg compounds that are peptide sequences. Seems to be missing from the list on line 1374 of kegg.py. It suggested to pass it along to the repo.

**Comment by cokelaer** [comment]
Hi James, 
Do you the name of the compound so that I can reproduce the bug ?
thanks

**Comment by JamesPino** [comment]
Sorry for the delay.
C16089
C00752
C02210
C02017

Are some examples. I also was wrong when I said it was parsing an KGML file. It is actually when using kegg.get.

**Comment by cokelaer** [comment]
Should be fixed now in the source code. A new release should be available on pypi
