### ISSUE TITLE
KEGG parse for keyword "SEQUENCE"

### ISSUE THREAD

**Issue by meono** [cokelaer/bioservices#51]
Hi,
I get the following warning for a few compounds (eg. C15682, C12045, ...) with parser:

```
from bioservices import KEGG
k=KEGG()
c = k.get('C15682')
cp = k.parse(c)
```

> Warning. Found keyword SEQUENCE, which has not special
>     parsing for now. please report this issue with the KEGG 
>     identifier (       C15682                      Compound) into github.com/bioservices. Thanks T.C.

**Comment by cokelaer** [comment]
Hi thanks for reporting this.
This is just a warning(that may be annoying) to catch fields that are not yet parsed. In this
example, SEQUENCE is therefore populated as it is (string). I will look into this particular so that the warning can be removed.  Thanks again.
