### ISSUE TITLE
Uniprot return integer

### ISSUE THREAD

**Issue by rickbeeloo** [cokelaer/bioservices#57]
I'm using bioservices after an automatic BLAST, it searches the accesionnumber in Uniprot and retreives the available data. However I check if their is a result using `if len(res) != 0`, this works well but sometimes I get the following error message: `if len(res) != 0: TypeError: object of type 'int' has no len()`.
But after printing the concerning variable (res) I turns out to be blank.
I hope someone know why this is happening?

**Comment by JamesPino** [comment]
I believe it is returning a 404 error. I have ran across this and fixed it by checking to see if it returns a dict or int.

**Comment by cokelaer** [comment]
Not sure what is the underlying code but I believe you can try to check if the output is None before checking its length:

    if res and len(res) != 0:

**Comment by cokelaer** [comment]
sorry, I closed the issue by mistake. Can you indicate the method you used ? I may add a line of code to make life easier.

**Comment by JamesPino** [comment]
Maybe it is at Uniprot.search? If res is returned as 404, this recreates the error `if len(res) != 0: TypeError: object of type 'int'`

As I mentioned before, for some searches to KEGG I have found similar errors. Maybe it is possible to add a class to check everything returned by http_get, ensuring it returns what is expected. if not raise warnings for all 404s?  Could refactor all if `if len(res) !=0` out and replace with check_http_return? Does something like this exist already? If not I  would be happy to implement.
