### ISSUE TITLE
Possible to access a KEGG entry without specifying the associated organism?

### ISSUE THREAD

**Issue by willigott** [cokelaer/bioservices#58]
I added a detailed question on [stackoverflow](http://stackoverflow.com/questions/37484095/how-to-access-a-kegg-entry-without-specifying-the-organism-using-bioservices).

In short:

Let's say I am interested in a certain gene (e.g. b3640) and I do not know to which organism it belongs, is it then possible to get all the information for this gene without specifying the organism?

For example

```
from bioservices import *
kegg_con = KEGG()
res = kegg_con.get('b3640', parse=True)['NAME']
```

does not work since the organism is not specified. When it is specified, it all works as intended

`kegg_con.get('eco:b3640', parse=True)['NAME']`

returns

`[u'dut']`

When I try to determine the associated organism by using

`kegg_con.find('genes', 'b3640')`

the desired entry is not found, unfortunately.

So my two questions are therefore:

1) Is there a way so that I can access the information about a gene just based on its gene ID without specifying the organism it belongs to?

2) What would be the best way to retrieve the information to which organism the gene belongs? And why doesn't find fails when I search for the E.coli gene?

**Comment by cokelaer** [comment]
Hi, 

You are right that settings the organism manually would work. Those two code are identical:

    from bioservices import *
    kegg_con = KEGG()
    kegg_con.organism = "eco"
    res = kegg_con.get('b3640', parse=True)['NAME']


    from bioservices import *
    kegg_con = KEGG()
    res = kegg_con.get('eco:b3640', parse=True)['NAME']

Now for the second problem, settings the organism or not to "eco", the following code works on my system

    genes = kegg_con.find('genes', 'b3640')
    
The output (string) contains eco:b3640 and contains 'dut'

so for your specific questions:
1) if the gene is part of KEGG, bioservices should return something and does for your example on my system (linux) bioservices source code v1.4.10
2) As far as I know, you were correct in using find("genes") method

I hope this helps. I'll answer to your  stackoverflow http://stackoverflow.com/questions/37484095/how-to-access-a-kegg-entry-without-specifying-the-organism-using-bioservices question in a minute.

**Comment by cokelaer** [comment]
Just posted an answer on the stackoverflow post. Please have a look

**Comment by willigott** [comment]
Already accepted, thanks a lot!
