### ISSUE TITLE
Typo in Kegg Tutorial

### ISSUE THREAD

**Issue by shlicshlac** [cokelaer/bioservices#59]
On the [KEGG tutorial page](https://pythonhosted.org/bioservices/kegg_tutorial.html#kegg-tutorial), 

```
k.organism = "hsa"
k.pathwaysIds
```
should be changed to 

```
k.organism = "hsa"
k.pathwayIds
```

**Comment by cokelaer** [comment]
Thanks for reporting this. This is fixed and will appear in the next doc release.
