### ISSUE TITLE
"Warning. Found keyword SYSNAME, which has not special parsing for now. please report this issue..."

### ISSUE THREAD

**Issue by willigott** [cokelaer/bioservices#60]
I received the following warnings which included the request to report them:

> Warning. Found keyword SYSNAME, which has not special
>     parsing for now. please report this issue with the KEGG 
>     identifier (       EC 4.2.1.3                  Enzyme) into github.com/bioservices. Thanks T.C.
> 
> Warning. Found keyword SUBSTRATE, which has not special
>     parsing for now. please report this issue with the KEGG 
>     identifier (       EC 4.2.1.3                  Enzyme) into github.com/bioservices. Thanks T.C.
> 
> Warning. Found keyword ALL_REAC, which has not special
>     parsing for now. please report this issue with the KEGG 
>     identifier (       EC 4.2.1.3                  Enzyme) into github.com/bioservices. Thanks T.C.
> 
> Warning. Found keyword HISTORY, which has not special
>     parsing for now. please report this issue with the KEGG 
>     identifier (EC 4.2.1.3                  Enzyme) into github.com/bioservices. Thanks T.C.

Here is the link to the entry: [kegg](http://www.genome.jp/dbget-bin/www_bget?ec:4.2.1.3).

**Comment by cokelaer** [comment]
Hi,do you happen to have the identifiers or code?

**Comment by cokelaer** [comment]
Oh I see the link you've posted

**Comment by cokelaer** [comment]
Fixed in the source code. The 4 fields will now be parsed and interpreted (mostly into lists)

**Comment by willigott** [comment]
Great, thanks!
