### ISSUE TITLE
UniProt TISSUE SPECIFICITY column

### ISSUE THREAD

**Issue by hutchenm** [cokelaer/bioservices#64]
I am using bioservices to query UniProt.  The curated column "comment(TISSUE SPECIFICITY) is useful to my searches, but trying to query this column using the u.search method results in an invalid field message.  The source for class uniprot (I am looking at https://pythonhosted.org/bioservices/_modules/bioservices/uniprot.html#UniProt)  has a "_valid_columns " property which includes many uniprot entry columns, but not his one.  

Would it be possible to include this column as a _valid_column in a future release?  Is there a better way, in the meantime, to get the data in this column, apart from getting the whole xml entry for each accession and then parsing it out myself?

**Comment by cokelaer** [comment]
sorry for the delay in the reply.
One way is to change _valid_columns variables:

u = UniProt()
u._valid_columns.append("name of your colum")

The list of valid ciolumns changes often within uniprot services. I have added your suggestion, which should be included in the next release 1.4.14

**Comment by hutchenm** [comment]
No problem for the timing, and thank you!
