### ISSUE TITLE
BioGRID Error 

### ISSUE THREAD

**Issue by enolette** [cokelaer/bioservices#68]
Off your example I get this error: 

b = BioGRID(query=["mtor","akt1"],taxId="9606",exP="two hybrid")
-----------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-4c707744833f> in <module>()
----> 1 b = BioGRID(query=["mtor","akt1"],taxId="9606",exP="two hybrid")

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bioservices/biogrid.py in __init__(self, query, taxId, exP)
     96         self.exP = exP
     97         self.searchString = self._biogridSearch()
---> 98         self.biogrid = Search(self.searchString)
     99 
    100     def _biogridSearch(self, query=None, taxid = None, exp = None):

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bioservices/biogrid.py in __init__(self, data)
     54         super(Search, self).__init__(verbose="ERROR")
     55         self.data = data
---> 56         if "biogrid" in self.activeDBs:
     57             self.output = self.query("biogrid",self.data)
     58         else:

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bioservices/psicquic.py in _get_active_db(self)
    259 
    260     def _get_active_db(self):
--> 261         names = self.registry_names[:]
    262         actives = self.registry_actives[:]
    263         names = [x.lower() for x,y in zip(names, actives) if y=="true"]

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bioservices/psicquic.py in _get_registry_names(self)
    324 
    325     def _get_registry_names(self):
--> 326         res = self.registry
    327         return [x.findAll('name')[0].text for x in res.findAll("service")]
    328     registry_names = property(_get_registry_names, 

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bioservices/psicquic.py in _get_registry(self)
    318             url = 'registry/registry?action=STATUS&format=xml'
    319             res = self.http_get(url, frmt="xml")
--> 320             res = self.easyXML(res)
    321             self._registry = res
    322         return self._registry

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bioservices/services.py in easyXML(self, res)
    183         """
    184         from bioservices import xmltools
--> 185         return xmltools.easyXML(res)
    186 
    187 

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bioservices/xmltools.py in __init__(self, data, encoding)
     77         #    self.data = x.fixed_string.encode("utf-8")
     78         #else:
---> 79         self.data = data[:]
     80 
     81         try:

TypeError: 'int' object is not subscriptable

**Comment by cokelaer** [comment]
I've noticed the same error locally. BioGrid module depends on the psicquic module/web service, which seems to be done. The same issue has been seen in other modules such as PRIDE. This seems to be an issue on EBI side. Hopefully, it should come back to normal very soon.

**Comment by enolette** [comment]
I see. Hopefully it is resolved soon. Thanks for the speedy response.

**Comment by cokelaer** [comment]
This works again so I presum it was bioGRID services that was down:

    b = BioGRID(query=['mtor', 'akt1'], taxId="9606", exP='two hybrid')
    b.biogrid.interactors  # give list of interactions
