### ISSUE TITLE
"Warning. Found keyword SYSNAME, which has not special..."

### ISSUE THREAD

**Issue by willigott** [cokelaer/bioservices#70]
A few more warnings (see below).

Warning. Found keyword SYSNAME, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 1.17.3.2                 Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword SUBSTRATE, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 1.17.3.2                 Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword ALL_REAC, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 1.17.3.2                 Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword HISTORY, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (EC 1.17.3.2                 Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword SYSNAME, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 3.5.1.87                 Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword SUBSTRATE, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 3.5.1.87                 Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword ALL_REAC, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 3.5.1.87                 Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword HISTORY, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (EC 3.5.1.87                 Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword SYSNAME, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 2.6.1.38                 Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword SUBSTRATE, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 2.6.1.38                 Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword ALL_REAC, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 2.6.1.38                 Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword HISTORY, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (EC 2.6.1.38                 Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword SYSNAME, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 3.5.3.5                  Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword SUBSTRATE, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 3.5.3.5                  Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword ALL_REAC, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 3.5.3.5                  Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword HISTORY, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (EC 3.5.3.5                  Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword SYSNAME, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 1.14.13.5                Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword SUBSTRATE, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 1.14.13.5                Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword ALL_REAC, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 1.14.13.5                Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword HISTORY, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (EC 1.14.13.5                Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword SYSNAME, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 6.3.4.8                  Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword SUBSTRATE, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 6.3.4.8                  Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword ALL_REAC, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 6.3.4.8                  Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword HISTORY, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (EC 6.3.4.8                  Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword SYSNAME, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 1.14.99.50               Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword SUBSTRATE, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 1.14.99.50               Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword ALL_REAC, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (       EC 1.14.99.50               Enzyme) into github.com/bioservices. Thanks T.C.

Warning. Found keyword HISTORY, which has not special
    parsing for now. please report this issue with the KEGG 
    identifier (EC 1.14.99.50               Enzyme) into github.com/bioservices. Thanks T.C.

**Comment by cokelaer** [comment]
With version 1.4.14 (pypi) I do not get any warnings. The field history, all_reac, substracte, sysname are well interpreted. Have you upgraded bioservices to the latest version ?

**Comment by willigott** [comment]
Was indeed a version issue (I used 1.14.11); sorry for the false-alarm.
