### ISSUE TITLE
BioServices Biomart

### ISSUE THREAD

**Issue by vladie0** [cokelaer/bioservices#71]
Dear Developers, 

Since Ensembl release version 86 I get the following error when attempting to connect to Ensembl:

performing:
s = BioMart()
s.lookfor()

generates the following error:
You must set the host (e.g. f.host='www.ensembl.org'

performing:
s=BioMart("www.ensembl.org")

generates the following output:
host www.ensembl.org is not reachable

However ensembl archives are reachable (e.g. older version of Ensembl (http://sep2015.archive.ensembl.org))

Is there a way to fix this ? 

Thanks in advance, 
Volodimir Olexiouk

**Comment by cokelaer** [comment]
The host www.ensembl.org seems down indeed. You can set host="uswest.ensembl.org" instead.
You may not have the same MARTs and datasets as in the example though. This is version 86.
best

**Comment by vladie0** [comment]
Dear cokelaer,

It seems that both version 86 and 87 from Ensembl are not reachable trough BioMart through your package. Does this mean that further version will not be supported anymore ? is there a way to access those database through the bioservices.biomart API ? 

FYI, manual access to the BioMart version of Ensembl 86-87 is possible.

Kind Regards,
volodimir olexiouk

**Comment by gunnarklee** [comment]
Dear Cokelaer

I have been having the same issue over the last two weeks. It seems that it is happening more often Is there a way to check or reset the system periodically?

**Comment by cokelaer** [comment]
I will close this recurrent issue that is related to biomarts changing their url rather than a biosercices issue. This is currently working for me and on Travis tests
