### ISSUE TITLE
 UniProt.get_df() and deleted entries

### ISSUE THREAD

**Issue by jlanga** [cokelaer/bioservices#72]
Hi Thomas.

My UniProt database seems updated. When looking for the deleted entry [L2LWX2](http://www.uniprot.org/uniprot/L2LWX2), if I use the `search` method, this is what I get

```python3
from bioservices import *
u = UniProt()
u.search("L2LWX2")
```

```
Entry	Entry name	Status	Protein names	Gene names	Organism	Length
L2LWX2	L2LWX2_ENTFC		Deleted.			
```

The problem comes when using the `get_df` method:

```python3
from bioservices import *
u = UniProt()
u.get_df("L2LWX2")
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-954106c98e6a> in <module>()
----> 1 u.get_df("L2LWX2")

/home/work/miniconda3/lib/python3.5/site-packages/bioservices/uniprot.py in get_df(self, entries, nChunk, organism)
    620         # Sequences are splitted into chunks of 10 characters. let us rmeove
    621         # the spaces:
--> 622         output.Sequence = output['Sequence'].apply(lambda x: x.replace(" ", ""))
    623 
    624         return output

/home/work/miniconda3/lib/python3.5/site-packages/pandas/core/series.py in apply(self, func, convert_dtype, args, **kwds)
   2290             else:
   2291                 values = self.asobject
-> 2292                 mapped = lib.map_infer(values, f, convert=convert_dtype)
   2293 
   2294         if len(mapped) and isinstance(mapped[0], Series):

pandas/src/inference.pyx in pandas.lib.map_infer (pandas/lib.c:66116)()

/home/work/miniconda3/lib/python3.5/site-packages/bioservices/uniprot.py in <lambda>(x)
    620         # Sequences are splitted into chunks of 10 characters. let us rmeove
    621         # the spaces:
--> 622         output.Sequence = output['Sequence'].apply(lambda x: x.replace(" ", ""))
    623 
    624         return output

AttributeError: 'float' object has no attribute 'replace'
```

I can get that `get_df` is not handling deleted entries properly. Also, you lose the annotation of all the other identifiers in your query without knowing which is the faulty one.

I don't know how a float ended up in `output['Sequence']`.  I hope that exact UniProt entry can help you when testing.

Thanks for all the work done!

Regards,

Jorge

**Comment by jlanga** [comment]
Hi Thomas.

I think I've fixed it, but unrelated tests are failing. [Here](https://github.com/jlanga/bioservices/commit/4547d886903b89436515225a134689d58d30062c) is the commit I made with a simple solution in my fork.

Pull request anyway?

Thanks,

Jorge

**Comment by cokelaer** [comment]
please go ahead with your pull request if you are still willing to create it . Otherwise, I will fix it in the next couple of weeks. thanks for reporting this issue anyway.

**Comment by cokelaer** [comment]
this was fixed. closing
