### ISSUE TITLE
warnings are printed to standard output instead of standard error

### ISSUE THREAD

**Issue by hmenager** [cokelaer/bioservices#82]
when using bioservices, warning (and probably error) messages are printed to standard output, which can result in side effects in tools where the result is printed to the standard output. Such messages include:
```
BioServices 1.4.16 warning: pandas is not installed on your system.
Some features requires this library and future version of BioServices may use it.
pandas library is not installed. Not all functionalities will be  available
```
It would be better to print these to stderr for instance, or use the logging package.

**Comment by cokelaer** [comment]
Using proper logging
