### ISSUE TITLE
AttributeError on KEGG Parser.

### ISSUE THREAD

**Issue by KeironO** [cokelaer/bioservices#92]
Hey there,

Apologies for this, but the KEGGParser seems to have an apparent bug.

```python
from bioservices import KEGG, KEGGParser

KEGGParser().parse(KEGG().get("C00626"))
```

Returns:

```
  File "/home/keo7/PycharmProjects/DIMEdb/db/generator.py", line 110, in generate_pathways
    KEGGParser().parse(KEGG().get("C00626"))
  File "/home/keo7/.local/lib/python2.7/site-packages/bioservices/kegg.py", line 1178, in parse
    entry = res.split("\n")[0].split()[0]
AttributeError: 'int' object has no attribute 'split'
```

Any help would be greatly appreciated.

Thanks,

Keiron.

**Comment by KeironO** [comment]
Well, I've just looked at it a bit more - it looks like if the compound isn't found it simply returns an integer value of 404.

How interesting.

**Comment by kirienko** [comment]
Hi,
it looks like the problem is in KEGG database itself, not in `bioservices`:
http://rest.kegg.jp/get/cpd:C00625 — works
http://rest.kegg.jp/get/cpd:C00626 — does not work
http://rest.kegg.jp/get/cpd:C00627 — works

So, probably, there's nothing to fix.
