### ISSUE TITLE
More on NBviewer link is broken

### ISSUE THREAD

**Issue by tobsecret** [cokelaer/bioservices#93]
This link from the repo gives me a 404:

http://nbviewer.jupyter.org/github/cokelaer/bioservices/tree/master/doc/source/notebook/

**Comment by cokelaer** [comment]
Hi, from where do you got the link ? The documentation on readthedocs or elsewhere ?
thanks

**Comment by tobsecret** [comment]
Oh, sorry - the link from the README.rst:

* UniProt on `uniprot nbviewer <http://nbviewer.ipython.org/url/pythonhosted.org//bioservices/_downloads/UniProt.ipynb>`_
* BioModels on `biomodels nbviewer <http://nbviewer.ipython.org/url/pythonhosted.org//bioservices/_downloads/BioModels.ipynb>`_
* ChEMBL on `chembl nbviewer <http://nbviewer.ipython.org/url/pythonhosted.org//bioservices/_downloads/ChEMBL.ipynb>`_
* Ensembl on `Ensembl nbviewer <https://github.com/bioservices/notebooks/tree/master/ensembl>`_
* KEGG on `KEGG nbviewer <http://nbviewer.ipython.org/url/pythonhosted.org/bioservices/_downloads/KEGG.ipynb>`_
* MUSCLE on `MUSCLE  nbviewer <http://nbviewer.ipython.org/url/pythonhosted.org/bioservices/_downloads/MUSCLE.ipynb>`_
* NCBIBlast on `ncbiblast nbviewer <http://nbviewer.ipython.org/url/pythonhosted.org/bioservices/_downloads/NCBIBlast.ipynb>`_
* WikiPathway on `wikipathway nbviewer <http://nbviewer.ipython.org/url/pythonhosted.org/bioservices/_downloads/WikiPathway.ipynb>`_

and more on `nbviewer <http://nbviewer.ipython.org/github/cokelaer/bioservices/tree/master/doc/source/notebook/>`_.

**Comment by cokelaer** [comment]
okay thanks I'll fix it for the next release. I will indeed move some notebooks here and there.

**Comment by cokelaer** [comment]
fixed README that will be updated on pypi with the next release
