### ISSUE TITLE
Issue with QuickGO interface

### ISSUE THREAD

**Issue by bonej079** [cokelaer/bioservices#94]
Hi,

It seems that EBI has made a change to the service, and a QuickGO search returns (what seems to be) the HTML for the main page. As a temporary workaround, the service is still accessible using the old site address:

s = QuickGO(verbose=True)

s.url = 'http://www.ebi.ac.uk/QuickGO-Old'

**Comment by MuhammadZeeshan34** [comment]
Thanks for suggesting this second solution.

**Comment by cokelaer** [comment]
currently working on using the new interface. The new interface is quite different from the previous one though. I will add a switch to keep the old one as well.

**Comment by cokelaer** [comment]
I finally copied the old version in quickgo_old.QuickGO_old and the new api is now in quickgo.QuickGO.
The new API provided is a draft version biut contains already some useful methods.

**Comment by Superraptor** [comment]
So I was utilizing this workaround, but it recently appeared to stop working? i.e. if I have `s = QuickGO(verbose=True)` and `s.url="http://www.ebi.ac.uk/QuickGO-Old`, then running `res = s.Term(new_id, frmt="obo")` results in the following trace:

```
    res = s.Term(new_id, frmt="obo")
AttributeError: 'QuickGO' object has no attribute 'Term'
```

Did the formatting/coding change significantly?
