### ISSUE TITLE
How to retrieve all ChEBI IDs for a given KEGG compound?

### ISSUE THREAD

**Issue by willigott** [cokelaer/bioservices#97]
Also posted [on stackoverflow](https://stackoverflow.com/q/46005142/1534017):

Let's say I want to map a KEGG ID to a ChEBI ID, I can do:

    from bioservices import *
    
    kegg_con = KEGG()
    kegg_entry = kegg_con.parse(kegg_con.get('C00033'))
    print kegg_entry['DBLINKS']['ChEBI'].split()

This will return

    [u'15366', u'30089']

meaning that there are two ChEBI IDs associated with the KEGG compound ([KEGG entry C00033](http://www.genome.jp/dbget-bin/www_bget?C00033)).

An alternative - if one has to do a lot of mappings - is to use the [built-in converter](https://pythonhosted.org/bioservices/convertor_tutorial.html) like this:

    map_kegg_chebi = kegg_con.conv("chebi", "compound")
    print map_kegg_chebi['cpd:C00033']

This will print

    u'chebi:15366'

So for the same compound, only one ID is returned although there are two associated with this compound. Is there a way to retrieve both of them?

**Comment by cokelaer** [comment]
In short, the 30089 is the ion form of the 15366 entries (acetate is the ion resulting from loss of H+ from the acetic acid) so the output of kegg_conv.conv is limited to the acetic acid form in that case. See the full answer on stackoverflow:

https://stackoverflow.com/questions/46005142/how-to-retrieve-all-chebi-ids-for-a-given-kegg-compound/46885147#46885147
